### ISSUE TITLE
Commenting gives bad credentials

### ISSUE THREAD

**Issue by paulstaab** [jimhester/lintr#102]
The commenting still does not work for me. On travis, I get
```R
$ Rscript -e 'lintr::lint_package()'
{
  "message": "Bad credentials",
  "documentation_url": "https://developer.github.com/v3"
}
```
Maybe this can be fixed by just issuing a new token for lintr-bot? I'm happy to look into the issue if this does not help.

**Comment by jimhester** [comment]
Yeah I would guess the token is the issue.  I will look into it in the next
day or so.

**Comment by paulstaab** [comment]
Any updates on this? Is there something I can do to help?

**Comment by paulstaab** [comment]
lintr-bot is commenting again! Thanks, I'll close this issue.

**Comment by jimhester** [comment]
Yes thank you for closing it and your patience. Sorry it took so long to get working again.
