### ISSUE TITLE
Exclude specific files from lintr?

### ISSUE THREAD

**Issue by zachmayer** [jimhester/lintr#107]
Is there a way to exclude specific files from linting?

**Comment by jimhester** [comment]
Yes, see `?lintr::exclude`

You can pass just the filename of the file to exclude to the exclude parameter, or specify it in the exclude block of your Project Configuration file https://github.com/jimhester/lintr/blob/master/README.md#project-configuration.

**Comment by zachmayer** [comment]
Thank you!



—
