### ISSUE TITLE
CRAN submission?

### ISSUE THREAD

**Issue by hadley** [jimhester/lintr#112]
I have 0.2.1 as a dep in devtools (don't remember why), but CRAN only has 0.2.0

**Comment by jimhester** [comment]
Think it was a caching thing with `devtools::lint()` I will submit the current code to CRAN, sorry for the delay!

**Comment by jimhester** [comment]
Ok 0.3.1 is on CRAN now https://github.com/jimhester/lintr/commit/3e6cb3d4f9d617533f4f6a107e2f05f028299286
