### ISSUE TITLE
How to configure which linters to use?

### ISSUE THREAD

**Issue by divenyijanos** [jimhester/lintr#120]
I use linter with Sublime 3. I have the following lines in my `SublimeLinter.sublime-settings` (in `Packages/Users`).

        "linters": {
            "lintr": {
                "@disable": false,
                "args": [],
                "cache": "TRUE",
                "excludes": [],
                "linters": "default_linters"
            }
        }

How can I select which linters I would like to use? [This](https://github.com/jimhester/lintr/issues/54) suggests that I should modify `"linters": "default_linters"` to `"linters": "list(object_usage_linter)"` but it has no effect.

I also tried  `"linters": "with_default(line_length_linter(120))"` and that works.

Is it possible to exclude some linters from default? I like my functions as camelcase, and do not want to get "no visible global definition" errors for functions which I source from other files or which are part of other packages (like `fread` from `data.table`).

**Comment by jimhester** [comment]
Are you sure `"linters": "list(object_usage_linter)"` has no effect? This would turn on _only_ that specific linter.

See `?lintr::with_defaults` for examples of enforcing camleCase. You need to turn off the object_usage_linter if you want to ignore the global definition warnings.

So `"linters": "with_defaults(camel_case_linter = NULL, object_usage_linter = NULL, snake_case_linter)"` seems to be what you are looking for.

**Comment by divenyijanos** [comment]
I tried also `"listers": "list(line_length_linter)"` just to experiment with it but it did not work either.

However, `"with_defaults()"` works great and your suggestion of setting some linters to `NULL` solves my problem. Thank you very much.

**Comment by kmace** [comment]
Is there a way to only have errors show? and disregard warnings?

**Comment by kmace** [comment]
answered my own question: with_defaults(default=NULL)
