### ISSUE TITLE
Allow specifying a global configuration

### ISSUE THREAD

**Issue by jimhester** [jimhester/lintr#124]
Only project level configurations are possible currently, should also be able to specify a global config file.

**Comment by hongyuanjia** [comment]
According to https://github.com/jimhester/lintr/blob/1a7114b87c4d672772c74ffc30c932dcdb3ce017/R/settings.R#L9, lintr actually has the capability to read the config file from user home directory. Is'nt working as a global configuration?

**Comment by AshesITR** [comment]
Probably forgotten to close (Issue from 2015, commit from 2019).
Feel free to create a new issue if it doesn't work as expected (i.e. .lintr is taken from any parent directory or from ~/.lintr)
