### ISSUE TITLE
Locally-disable

### ISSUE THREAD

**Issue by terrytangyuan** [jimhester/lintr#126]
Hi Jim, 

Is it possible to disable lint analysis locally like pylint does for Python? 

Thanks,
Yuan

**Comment by saurfang** [comment]
Are you talking about disable lint for a region of code blocks? Is so, looks like this is what you're looking for: https://github.com/jimhester/lintr#project-configuration

**Comment by terrytangyuan** [comment]
That is it! Somehow I missed it. Thanks!
