### ISSUE TITLE
\Sexpr tag in Roxygen Block Causing An Error

### ISSUE THREAD

**Issue by rtaph** [jimhester/lintr#127]
Hi Jim,

Thanks for your wonderful package. I use it all the time.

I added a `\Sexpr` tag inside of my roxygen documentation block in order to [generate dynamic content in my man pages](https://cran.r-project.org/doc/manuals/R-exts.html#Dynamic-pages), but this is causing line 4 of `extract_r_source()` to return a non-NULL value. As a result, `lint_package()` and `expect_lint_free()` throw back an error for the file that contains the line `#' text \Sexpr{1 + 1} more text`.

I realize that the regex is not your own, as it is imported from the `knitr` package via `knitr::all_patterns$rnw$inline` code. Nevertheless, is there a way around having Roxygen blocks with `\Sexpr` tags from throwing this error?

Thanks in advance,

**Comment by jimhester** [comment]
Thanks for the report, I will see what can be done.

**Comment by gaborcsardi** [comment]
Yeah, I see this, too...

**Comment by jimhester** [comment]
Ok should be fixed now, sorry for the _lengthy_ delay :smile:
