### ISSUE TITLE
Unable to turn off @lintr-bot

### ISSUE THREAD

**Issue by krlmlr** [jimhester/lintr#132]
This guy keeps on commenting, no matter what I try. My last attempt so far was:

```
Rscript -e 'Sys.setenv(LINTR_COMMENT_BOT="FALSE"); if (!requireNamespace("lintr")) devtools::install_github("jimhester/lintr"); lintr::lint_package()'
```

It looks like `default_settings` are defined in such a way that they are fixed during *package installation time*, which might explain the behavior I'm seeing: https://github.com/jimhester/lintr/blob/7fe9bd4320de58336a7caf104ab7bc8fb471953c/R/zzz.R#L85-L103

**Comment by jimhester** [comment]
You are right, the settings should be moved to .onLoad().

**Comment by jimhester** [comment]
If you set `comment_bot: FALSE` in your project config that should turn it off as well, but a769c0b evaluates the default settings on load so the above should now work.

**Comment by AbdealiJK** [comment]
How would I set comment_bot to False if I am running it on a single file ? (on the current stable version)

**Comment by jimhester** [comment]
@AbdealiJK setting `LINTR_COMMENT_BOT=FALSE` should work now, so that is all you should need to do.
