### ISSUE TITLE
Lintr seems to not work in sublime text 3 (3103)

### ISSUE THREAD

**Issue by tvby** [jimhester/lintr#140]
Since R is not in my PATH environment I added it to paths in sublimelinter for windows with the folliowing:
```
"paths": {
                "linux": [],
                "osx": [],
                "windwows": [
                    "C:/Program Files/R/R-3.2.4revised/bin/x64/"
                ]
            }
```

I then installed lintr using the following:
```
library("devtools", lib.loc="~/R/win-library/3.2") 
install_github('jimhester/lintr') 
```

which installs lintr and what appears to be some dependencies
Finally, having done this I used package control  to install SublimeLinter-contrib-lintr which is listed
in the SublimeLinter.sublime-settings as the following
```
"lintr": {
                "@disable": true,
                "args": [],
                "cache": "TRUE",
                "excludes": [],
                "linters": "default_linters"
            }

```
Having done all of this I created the bad.R file and chose Tools -> SublimeLinter -> Lint this view 
and nothing happens. Am I missing a part of this setup?

**Comment by isezen** [comment]
Should be `"@disable": false`

**Comment by tvby** [comment]
That solved the problem.

**Comment by irfe92** [comment]
Hello, lintr in not working; I get this message : No lint results.
these are my user settings...
Can someone help me please?
{
  "linters": {
    "lintr": {
      "linters": "with_defaults(assignment_linter = NULL, line_length_linter(120))",
                "@disable": false,
                "args": [],
                "cache": "TRUE",
                "excludes": [],
                "linters": "default_linters",
                "paths":{"windows":["C:\\Program Files\\R\\R-3.5.1\\bin\\x64"]}         
    }
  }
}
