### ISSUE TITLE
add a cool profile picture to lintr bot

### ISSUE THREAD

**Issue by masalmon** [jimhester/lintr#142]
I guess a nice face would be better for feeling motivated.

**Comment by jimhester** [comment]
I thought current image wasn't too imposing, but happy to change it to something cherrier!
![image](https://cloud.githubusercontent.com/assets/205275/14250167/2ecd8ff6-fa4b-11e5-9216-cffd151f8794.png)

Any suggestions?

**Comment by masalmon** [comment]
Oh last time the bot wrote to me there was NO picture so I forgot to look at this one. Where does it come from? It lacks eyes and a smile. ;-) Or it could be the same as it is now but wearing a flag saying "code style"? Just being picky. I can try something in Paint...

**Comment by masalmon** [comment]
wait I have an idea!

**Comment by masalmon** [comment]
This is ugly but now it's not a simple robot. ;-) Maybe Power Point would be better than Paint. 

![botlintr](https://cloud.githubusercontent.com/assets/8360597/14250737/169bd4a8-fa80-11e5-8cbd-7bc5d69e2b2c.png)

**Comment by jimhester** [comment]
Haha that is awesome! I think the text may be too small to see as an icon unfortunately. https://github.com/jackwasey/icd/commit/d976ea11dd2034354e32529d7ea0caf83cb7b1ac#commitcomment-16952925 is how it looks in a comment

**Comment by masalmon** [comment]
Oh good point but what if the shield simply says lintr?

I now want a small bot sticker :-D

**Comment by jimhester** [comment]
Just saying lintr could work, or maybe just an L?

**Comment by masalmon** [comment]
Ok, I'll try to make this work. The version of the robot you posted at the beginning is the highest resolution version, right?

**Comment by jimhester** [comment]
Source image is https://pixabay.com/en/cute-cartoon-robot-funny-character-807306/, which is much higher resolution.

**Comment by masalmon** [comment]
ahahah "cute-cartoon-robot" -> I imagine what your search was :-D

**Comment by masalmon** [comment]
1) I'm so not a designer...
2) It might have lost resolution

![botlintr](https://cloud.githubusercontent.com/assets/8360597/14251744/af393936-fa84-11e5-94ec-bf71c3831d34.png)

**Comment by masalmon** [comment]
@lintr-bot 😆
