### ISSUE TITLE
x == NA instead of is.na(x)

### ISSUE THREAD

**Issue by jabranham** [jimhester/lintr#143]
It would be useful to have a linter that checks for `x == NA` where I meant to write `is.na(x)`. Is that possible?

**Comment by jimhester** [comment]
It is definitely possible and probably correct in most cases. Can you think of any cases where you actually would want to use `x == NA` instead of `is.na(x)`?

**Comment by jabranham** [comment]
I can't - `x==NA` will just return `NA`s for all values of `x`. That doesn't seem helpful to me.
