### ISSUE TITLE
emacs - Flycheck Lintr Linters option is empty

### ISSUE THREAD

**Issue by yitang** [jimhester/lintr#144]
Hi, thanks for writing this package. I am follwoing the readme to configure lintr in Emacs, but can't find the `flycheck-lintr-linters` is empty, see blow.

![image](https://cloud.githubusercontent.com/assets/6054101/14940449/a6c1e3d6-0f6d-11e6-8eed-676af59b9052.png)

**Comment by jimhester** [comment]
Looks like it is set to `default_linters` to me. See https://github.com/jimhester/lintr#available-linters and `?with_defaults` for information on the default linters and setting options.

**Comment by yitang** [comment]
takes me a while to realise I need to see the default options in R, not in Emacs...

Thanks!
