### ISSUE TITLE
Semicolons at the end of the line?

### ISSUE THREAD

**Issue by gaborcsardi** [jimhester/lintr#147]
Would you like to see a PR for it?

**Comment by jimhester** [comment]
Sure,  that is a good one actually!

**Comment by gaborcsardi** [comment]
How about non-trailing semicolons? Personally I think that these are quite often fine, but sometimes not.
Should we report these? Have a separate linter for them? Ignore them completely?

**Comment by jimhester** [comment]
I think non trailing are fine as well

**Comment by gaborcsardi** [comment]
Closed by #148.
