### ISSUE TITLE
Lint for external function?

### ISSUE THREAD

**Issue by hanfeisun** [jimhester/lintr#150]
I'm using the lintr integrated with Rstudio 0.99.896

Let's say, I have a function in `util.R`:
```
if(!exists('util_loaded')){
  util_loaded<-T
  hello <- function() {cat("hello")}
}
```

Then I used this function in `app.R`:

```
source('./util.R')
hello()
```
 

Then the Rstudio will throw a warning: 

`no symbol named 'hello' in scope
`

I was wondering whether this is intended or if there is a way to fix it...

**Comment by jimhester** [comment]
The linter built into RStudio is not this codebase or package. You need to open this issue at https://support.rstudio.com
