### ISSUE TITLE
subtree matching or maybe use getParseData(..., includeText=TRUE)

### ISSUE THREAD

**Issue by gaborcsardi** [jimhester/lintr#153]
I am working on some linters that require matching a (sub-)tree to the parse tree, e.g. `1:length(expr)`, `x == NA`, etc. 

It would be nice to have some generic solution for this. 

One nice solution would be to implement a (labeled) subtree isomorphism algorithm, and then you could just declare that you want all sub-expressions that have a tree like `1:length(expr)`, where `expr` is an `expression` token.

But this is relatively difficult, and might be slow in R. igraph has algorithms for this, although not tree specific, but still quite fast for trees. But I don't want to bring back the igraph dependency.

So I am leaning towards a more hackish solution. E.g. it would be easy to search for the text of a subtree, using regular expressions, and then do some extra checks. E.g. for `1:length(expr)` you would need to search for `1:length[(](.*)[)]` in `parsed_content$text`, and then check that the captured group is an `expr` token and a grandchild of the matched expression. The drawback of this solution is that the regexp has to be resistant to whitespace, i.e. for the `1:length()` checker it should be rather something like `1\\s*:\\s*length[(](.*)[)]` and this can be painful and easy to mess up. Not to mention cases like `1 : # comment \n length(x)`, which are hard even with the subtree matching.

Also, the hackish solution would need the text of all subtrees. Would you consider calling `getParseData` with `includeText = TRUE`?

**Comment by gaborcsardi** [comment]
Here is another idea. How about converting the parsed data to XML? Then we could just search it with xpath expressions. I think just converting it to XML is very useful.

I hate XML, so if you know an alternative that is tree-stuctured and subtree searchable, that would be great, too. :)

**Comment by jimhester** [comment]
`includeText = TRUE` is fine, but IIRC the text is limited to 500 characters, so relying on it can fail for large subtrees (although that shouldn't be applicable to the cases you have mentioned).

Converting to XML sounds like it could be useful to me. You could probably use JSON as well, although there doesn't seem to be a standard equivalent to xpath (http://stackoverflow.com/questions/8481380/is-there-a-json-equivalent-of-xquery-xpath).

While in general I agree XML is cumbersome to work with, for this case I don't think it would be too terrible and would probably allow more efficient searches.

**Comment by gaborcsardi** [comment]
OK, first version of the XML tree creator: https://github.com/MangoTheCat/xmlparsedata

It is pretty slow, ~17 sec for `QC.R`, the ultimate benchmark. I am afraid that it must be rewritten in C/C++ to make it significantly faster....

```r
p <- parse(text = "function(a=1, b=2) { a + b }", keep.source=TRUE)
cat(xml_parse_data(p))
#> <?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
#> <exprlist>
#> <expr pos="1:1-1:28">
#>   <FUNCTION pos="1:1-1:8">function</FUNCTION>
#>   <OP-LEFT-PAREN pos="1:9-1:9">(</OP-LEFT-PAREN>
#>   <SYMBOL_FORMALS pos="1:10-1:10">a</SYMBOL_FORMALS>
#>   <EQ_FORMALS pos="1:11-1:11">=</EQ_FORMALS>
#>   <expr pos="1:12-1:12">
#>     <NUM_CONST pos="1:12-1:12">1</NUM_CONST>
#>   </expr>
#>   <OP-COMMA pos="1:13-1:13">,</OP-COMMA>
#>   <SYMBOL_FORMALS pos="1:15-1:15">b</SYMBOL_FORMALS>
#>   <EQ_FORMALS pos="1:16-1:16">=</EQ_FORMALS>
#>   <expr pos="1:17-1:17">
#>     <NUM_CONST pos="1:17-1:17">2</NUM_CONST>
#>   </expr>
#>   <OP-RIGHT-PAREN pos="1:18-1:18">)</OP-RIGHT-PAREN>
#>   <expr pos="1:20-1:28">
#>     <OP-LEFT-BRACE pos="1:20-1:20">{</OP-LEFT-BRACE>
#>     <expr pos="1:22-1:26">
#>       <expr pos="1:22-1:22">
#>         <SYMBOL pos="1:22-1:22">a</SYMBOL>
#>       </expr>
#>       <OP-PLUS pos="1:24-1:24">+</OP-PLUS>
#>       <expr pos="1:26-1:26">
#>         <SYMBOL pos="1:26-1:26">b</SYMBOL>
#>       </expr>
#>     </expr>
#>     <OP-RIGHT-BRACE pos="1:28-1:28">}</OP-RIGHT-BRACE>
#>   </expr>
#> </expr>
#> </exprlist>
```

**Comment by jimhester** [comment]
The current development version of xml2 has support for generating XML, although I am not sure if it would actually be faster for this use case or not.

I think we might want to have separate attributes for line and column starts and ends.

Even if the XML creation is slow it only has to be done once per file so if it ends up speeding the linters it can still be an overall win.

**Comment by gaborcsardi** [comment]
Most of the running time is spent in `paste0` and indexing data frames, so a C solution will be much-much faster, especially if we can just append the output to a file sequentially.

I could also try using a `textConnection()` first in R.

Or the XML creation. Is that `libxml2` stuff or your R code? :)

I'll separate the starts and ends. Do you want separate line and column numbers as well?

**Comment by gaborcsardi** [comment]
> I think we might want to have separate attributes for line and column starts and ends.

Oh, I see what you mean, everything separate. Indeed it makes more sense. I just added it.

I see that the XML creation is wrapping `libxml2`.

**Comment by gaborcsardi** [comment]
I tried `rawConnection()` and some other speed improvements, so `QC.R` is down to ~ 7 seconds now, but this seems to be the limit. 60% of the time is `writeChar`....

So it is either `xml2`, or just C code.

**Comment by gaborcsardi** [comment]
Another idea. Maybe we can vectorize the whole thing. :)

**Comment by gaborcsardi** [comment]
OK, the vectorized solution is pretty fast, 0.6 - 0.7 sec for `QC.R`. It only relies on positions, and ignores the parent pointers completely.

In theory this could be problematic if a non-terminal node is a child of another non-terminal node and they have the exact same positions, both start and end. But I don't know of any such case, it is probably not possible for a bison grammar.

It would be quick to check that the order is correct, we just check that the parents are printed before the children.

This is R code only. With C code it would be probably much faster.

**Comment by gaborcsardi** [comment]
Works very well! E.g. finding `1:nrow(...)` forms:

```r
p <- parse("~/src/r-source/src/library/tools/R/xgettext.R", keep.source=TRUE)
xx <- xml_parse_data(p)
x2 <- read_xml(xx)
xml_find_all(x2, "//expr[expr[NUM_CONST[text()='1']]][OP-COLON][expr[expr[SYMBOL_FUNCTION_CALL[text()='nrow']]]]")
#> {xml_nodeset (1)}
#> [1] <expr line1="334" col1="19" line2="334" col2="27">\n                <expr ...
```

XPath syntax is not the most readable, but this is still so much better than having to write this search manually!

**Comment by gaborcsardi** [comment]
Finishing things up. Two big issues remain as I see, but you might know more:
- UTF-8 source. I see lintr has some code to convert from bytes to chars. I am not sure if we need to know anything for the XML, though.
- Comments with negative parent pointers. I guess R tries to match them to the corresponding object. I am not sure what we should do with them. Currently they are ignored completely.

**Comment by gaborcsardi** [comment]
FYI, I am done with this, so unless you want to change sg, I'll submit it to CRAN. 
I didn't put it in lintr, because it will be useful in multiple packages.

**Comment by jimhester** [comment]
Sounds good! I agree it is generally useful for sure.

**Comment by gaborcsardi** [comment]
Thanks! Of course I have issues with UTF-8 on windows.....so I need to sort that out. Is this why you convert from bytes to characters in lintr?

**Comment by jimhester** [comment]
Probably, I still don't have a great feel on the best practice for encodings in R though...

**Comment by jimhester** [comment]
Also I don't know what you ended up doing for comments, but it would be handy for some cases (I still want to write a [gofmt](https://golang.org/cmd/gofmt/) for R at some point...)

**Comment by gaborcsardi** [comment]
Re comments: only top level comments are problematic AFAICT. I attach them to the top level now, i.e. set their parent to zero. I suspect R tries to associate them to the next top level non-comment expression, hence the negative parent. But even without the negative parent, it is kinda easy to do this, it is just the next non-comment sibling in the XML.

Re gofmt. Cool. Btw. isn't formatR enough for this?

**Comment by gaborcsardi** [comment]
Btw. I am wondering what the best way would be to use the XML stuff in lintr. For now I guess my linter will just call `xml_parse_data` on `parsed_content`. 

But as you said it would make sense to run it once, and not in every linter.

**Comment by jimhester** [comment]
formatR is very limited, it uses hacks to parse the comments (See 6, 7 at http://yihui.name/formatR/) that restrict where you can place comments and what they can contain. It also can only format based on base::deparse() so custom formatters cannot be written.

In addition gofmt allows you to specify arbitrary rewrite rules to apply code transformations e.g.
```bash
gofmt -r 'a[b:len(a)] -> a[b:]' -w $GOROOT/src
```

**Comment by jimhester** [comment]
Parse it once in https://github.com/jimhester/lintr/blob/master/R/get_source_expressions.R#L80-L106 and add it to the returned list (as xml_parsed_content maybe?)

**Comment by gaborcsardi** [comment]
Wow. `gofmt` looks pretty cool. The XML tree could be indeed useful for that.

I'll submit a PR for `xml_parsed_content`, maybe after the thing is on CRAN, so we don't have to mess with `Remotes`. 

Btw. the `QC.R` xml2 object is about 22MiB in memory, not too bad. Surprisingly, because the XML is really verbose.

**Comment by gaborcsardi** [comment]
Do you want `xml_parsed_content` be the XML string or an `xml2` document? I guess the latter makes more sense, because you would need to create an XML document to do anything meaningful with it.

**Comment by jimhester** [comment]
`xml2` document like you said.
