### ISSUE TITLE
Lintr Configuration

### ISSUE THREAD

**Issue by JLCCI** [jimhester/lintr#158]
Many thanks for the absolutely amazing package, makes work much easier.

I am using lintr with Atom and wanted to ask how to turn off two linting options in the configuration file:
1) "Commented code should be removed"
2) "Variable and function names should be all lowercase." - most of the libraries I use does not seem to follow this so I have hundreds of warnings.

Many thanks for your help.

**Comment by jabranham** [comment]
Looks like you can turn this off pretty easily. There's instructions and an example in the readme: 
https://github.com/jimhester/lintr#project-configuration

**Comment by jimhester** [comment]
Thank you @jabranham!  Additionally if you want to turn this off globally when using Atom see the documentation a https://atom.io/packages/linter-lintr#settings
