### ISSUE TITLE
Question on applying lintr to lintr package itself

### ISSUE THREAD

**Issue by dy-kim** [jimhester/lintr#162]
Hi,
While I was reading sources of `lintr` package, I found quite many `blank_line`s, assignment violations and so on which all is expected to be listed in the `Markers` (I'm using Rstuido) after running `lint_package()` in the `lintr` package project. 
But the `Marker` was clean. I even tried `lint_package(linters = trailing_blank_lines_linter)` and empty again.

In the line 6 of [`trailing_blank_lines_linter.R`](https://github.com/jimhester/lintr/blob/master/R/trailing_blank_lines_linter.R) code , I think there is a `trailing blank line`. (Am I misunderstanding the meaning of trailing blank lines?)

How could this happen?

**Comment by jimhester** [comment]
Trailing blank lines only occur at the end of a file. Blank lines in the middle of a file are important to break code into logical chunks and improve readability. It is working as intended.
