### ISSUE TITLE
Failed with GitLab CI

### ISSUE THREAD

**Issue by artemklevtsov** [jimhester/lintr#166]
I tried to use `lintr` for the package testing with the GitLab CI. I got the following error:

``` r
$ Rscript -e 'lintr::lint_package()'
Error in httr::status_code(response) : object 'response' not found
Calls: <Anonymous> -> print.lints -> github_comment -> <Anonymous>
Execution halted
```

Now `ci_type()` support only Travis CI and Wercker CI on Github.

Seems reason of the error in the following rows:
- https://github.com/jimhester/lintr/blob/a769c0b8be6740329d8d855f230e6ff3c31175c1/R/methods.R#L60
- https://github.com/jimhester/lintr/blob/a769c0b8be6740329d8d855f230e6ff3c31175c1/R/methods.R#L70

I find a simple workaround: to unset `CI` environment variable.

**Comment by xanderdunn** [comment]
I have this same issue in CircleCI 2.0.  Adding `export CI=""` before the lint step also worked for me.
