### ISSUE TITLE
No discrimination against camelCase

### ISSUE THREAD

**Issue by eddelbuettel** [jimhester/lintr#17]
Would you consider an option to _precisely revert_ this one:

> object_name_linter: check that objects
> Are never camelCase
> Are separated by _ rather than .
> Are not more than width characters

Not everybody is a fan of snake_case, and a casual reading of R code demonstrated that no one style dominates. So maybe we should not impose one particular preference?

(I am less obsessed wit subpoints 2 and 3.  I too dislike the dot as a word separator is it is confusing vis-a-vis the dispatch mechanism, but I am neutral on `maxWidth`.  Or, as you would call it, `max_width`.

**Comment by achevali** [comment]
Is this implemented and if so how do I enforce it?
