### ISSUE TITLE
Incorrect parsing when unnecessary parenthesis are involved

### ISSUE THREAD

**Issue by sfr** [jimhester/lintr#172]
Using **lintr 1.0.0**, following code: 

``` R
execBatch <- ((i %% batchSize) == 0) || (i == nrow(value))
```

apart from complaining about camel case (which is OK) complaints about spaces:

`Place a space before left parenthesis, except in a function call.`

When removing unnecessary parenthesis everything is OK.

``` R
execBatch <- (i %% batchSize) == 0 || i == nrow(value)
```

**Comment by jimhester** [comment]
This no longer occurs in the current master.
