### ISSUE TITLE
Error in spaces_left_parentheses_linter()

### ISSUE THREAD

**Issue by rmsharp** [jimhester/lintr#175]
The following incorrectly is noted as an error because of the space to the left of the left parenthesis:
nSuffix <- ((nDigits + 2) %/% 3) - 1

**Comment by gdkrmr** [comment]
related:
`exp(-(a ^ 2))`
gives the same error

**Comment by HenrikBengtsson** [comment]
... and `x[-(1:2)]`.

**Comment by HenrikBengtsson** [comment]
This appears to be a duplication of https://github.com/jimhester/lintr/issues/77 - "Space before parenthesis: c((x + y) * z)".

**Comment by jimhester** [comment]
This is fixed in the latest master.
