### ISSUE TITLE
expect_lint() should be exported

### ISSUE THREAD

**Issue by fangly** [jimhester/lintr#178]
Hi,

I am writing some custom linters following the document at https://cran.r-project.org/web/packages/lintr/vignettes/creating_linters.html . It turns out to be impossible to add testthat tests because the "expect_lint()" expectation is not exported by lintr.

I am thus forced to use the lintr:::expect_lint hack at the moment.

Could you please add a small "#' @export" statement in "R/expect_lint.R" please?

Cheers,

Florent

**Comment by jimhester** [comment]
Sure I could do it, but since you seem to know what to do why not make a pull request instead? See http://r-pkgs.had.co.nz/git.html#git-pullreq and https://help.github.com/articles/creating-a-pull-request/ for information on how to create one.

Because this change requires re-documenting don't forget to run `devtools::document()` or `roxygen2::roxygenize()` on the package and commit the `NAMESPACE` changes as well.

**Comment by fangly** [comment]
Unfortunately, I am behind an institutional proxy/firewall that makes cloning/pushing github repos impossible.
Cheers,
Florent

**Comment by gaborcsardi** [comment]
@fangly For this simple change, you can just edit the file(s) online.

**Comment by fangly** [comment]
Thanks gaborcsardi, but I would need to make a fork first. And then I wouldn't be able to run devtools::document() anyway.

**Comment by fangly** [comment]
To follow up on this issue, the tutorial I mentioned above also list the "ids_with_token" function, which is defined in R/utils.R, but not exported.
Again, it might be useful to export this function so that the tutorial can be completed. Cheers!

**Comment by fangly** [comment]
Well, I suppose you need to decide then:
1/ Either update the tutorial and clarify that this is intended for contributing linters to lintr (and then the first described step should be to fork). Then you can keep "expect_lint" and "ids_with_token" private.
2/ Or export "expect_lint" and "ids_with_token" and make sure that the tutorial works for people writing a custom linter on their own.

Considering that not everyone may be able to contribute the linter they wrote, and you may not want to accept the linters written by everyone, I would be in favor of option 2.

Cheers,

Florent

**Comment by jimhester** [comment]
@russHyde Feel free to close them yourself!
