### ISSUE TITLE
Improved & generalized semicolon linter [patch]

### ISSUE THREAD

**Issue by fangly** [jimhester/lintr#181]
Hi,

I noticed that trailing_semicolons_linter() missed some cases (when the statements are not enclosed in "function(){}"). Further, I wanted to be able to report compound semicolons, semicolons between two statements on the same line.

So, this is what I did:
    \* added more tests to trailing_semicolons_linter()
    \* had to improve trailing_semicolons_linter()'s code to pass all tests
    \* generalized trailing_semicolons_linter() so that it also detects compound semicolons
    \* added the option to report compound semicolons, trailing, or both
    \* renamed it to semicolon_linter() to match the new functionality

The result is in this patch: [0001-Improved-generalized-trailing_semicolons_linter-now-.zip](https://github.com/jimhester/lintr/files/548047/0001-Improved-generalized-trailing_semicolons_linter-now-.zip)

Best,

Florent

**Comment by jimhester** [comment]
If you name the files `.patch` and don't zip them, I think GitHub will automatically render them in-line.

**Comment by fangly** [comment]
Unfortunately, GitHub does not support ".patch" file type.
I have tried ".txt", which is allowed but the content is not shown in-line.
Florent

**Comment by fangly** [comment]
Fixed in #214
