### ISSUE TITLE
lint identification vs fixing

### ISSUE THREAD

**Issue by edlee123** [jimhester/lintr#186]
Hello Jim,

When using lintr functions to identify lints, is there a good way to automate actual fixing the lints?

I use formatR and RStudio, and while they can automatically format some things, their lint identification functions are not as comprehensive as lintr's.  Would be interested if there is a good approach 

-ed

**Comment by jimhester** [comment]
Nothing exists in lintr currently to do this. I wrote a blog post on doing this robustly for the assignment linter (http://www.jimhester.com/blog/2016/07/25/assignment/). The same idea could be extended for most of the other lints in the package.

**Comment by edlee123** [comment]
Ah cool, I'll experiment a bit with this idea, cheers jim

**Comment by kenahoo** [comment]
I came here to ask the same question, and discovered this ticket.  It would be great if `lintr` itself could be in charge of correcting formatting according to a given policy, so that the policy, the checking, and the fixing could be ensured to be in sync.

**Comment by russHyde** [comment]
You could use the CRAN package [styler](https://cran.r-project.org/web/packages/styler/index.html) to do an initial formatting; this does tend to address a lot of the lints I see in practice.
