### ISSUE TITLE
single line .lintr without trailing linebreak

### ISSUE THREAD

**Issue by gdkrmr** [jimhester/lintr#189]
a `.lintr` file with a single line without trailing `\n` gives the following error, when calling `Rscript -e 'lintr::lint_package()'`:
```
Error in mapply(function(from, to) paste(lines[from:to], collapse = "\n"),  : 
  zero-length inputs cannot be mixed with those of non-zero length
Calls: <Anonymous> -> read_settings -> read.dcf -> mapply
Execution halted
```

**Comment by jimhester** [comment]
This seems to be a duplicate of https://github.com/jimhester/lintr/issues/160
