### ISSUE TITLE
Suggestion: ignore linters due to imported functions

### ISSUE THREAD

**Issue by ThierryO** [jimhester/lintr#191]
Since there is no common coding style in R, importing functions from other packages often results in a clash of coding styles. Currently we have to `#nolint` the offending functions, which is a bit tedious. All imported functions are listed in `NAMESPACE` so that would be nice place to look for the exceptions.

**Comment by jimhester** [comment]
An alternative is to use `::` or `:::` to refer to functions they will automatically [excluded from the object linters](https://github.com/jimhester/lintr/blob/7fe7e9093c7e9f41eebe600d89a98375d68f8f40/R/objects_linter.R#L114-L118). This style is the recommended one in Hadley's [R Packages](http://r-pkgs.had.co.nz/namespace.html#import-r) book.

Excluding functions imported into the package NAMESPACE is possible of course, but lintr currently works on a file a time and does not handle package structure at all, so it would require some changes in how things work.

**Comment by fangly** [comment]
@ThierryO I like your suggestion!
@jimhester It would make sense if the `lint_package` function automatically dealt with the `NAMESPACE` and somehow added imported functions to the `exclude` function (although `exclude` currently only works on entire files and lines).

**Comment by ThierryO** [comment]
@jimhester Note that in the second paragraph Hadley writes: 

> If you are using functions repeatedly, you can avoid :: by importing the function with @importFrom pgk fun.

Would you accept a pull request which takes into account the imports from `NAMESPACE`? I'm willing to try implementing that.

**Comment by jimhester** [comment]
I think what @fangly Suggested makes sense, if the `lint_package()` parses the NAMESPACE file once they can then be added to the exclusion objects.

**Comment by fangly** [comment]
Come to think of it, if that's of the objects_linter.R (name length, camel case, etc) that we are talking about, there may be a better strategy. I do also get a lot of lints from function calls, dataframe accesses, etc that I did not create.
It seems like it would be preferable to lint only objects that are _assigned_, not just merely used or called. To illustrate this, in this example, we would only check the names of f, a, b and x:
`f <- function(a, b) {x <- 1}`
Likely, the "make_object_linter" function could be adapted for this purpose.

**Comment by fangly** [comment]
I updated my `object_name_linter()` to only lint _assigned_ object, as described in my previous comment.

**Comment by fangly** [comment]
Fixed in #214
