### ISSUE TITLE
commas_linter.R

### ISSUE THREAD

**Issue by LiNk-NY** [jimhester/lintr#192]
Hi Jim @jimhester, 
The `commas_linter` works great but there are some special cases where: 
"check that all commas are followed by spaces, but do not have spaces before them"  
should not be satisfied. 
For example:
```
array[ , , z] 
```
So I guess the rule would be, "...unless it's after another comma `,` or a backet `[`". 
Thanks!

**Comment by rentrop** [comment]
I gutess this was closed in the new development version:
https://github.com/jimhester/lintr/commit/600cb8227100025ff33faa30376afebe5f0a7ddb

https://github.com/jimhester/lintr/issues/145

**Comment by HenrikBengtsson** [comment]
Confirming that this has been fixed in the `master` branch.

# lintr 1.0.0
```r
> packageVersion("lintr")
[1] '1.0.0'

> cat("y <- x[, , 1]\n", file = "commas.R")
> p <- lintr::lint("commas.R")
> p
commas.R:1:10: style: Commas should never have a space before.
y <- x[, , 1]
> length(p)
[1] 1
```

# lintr 1.0.0.9001
```r
> packageVersion("lintr")
[1] '1.0.0.9001'
> p <- lintr::lint("commas.R")
> p
> length(p)
[1] 0
```

**Comment by russHyde** [comment]
Closed with ref to https://github.com/jimhester/lintr/issues/253
