### ISSUE TITLE
lintr::lint - note that the linters list arg has to be a named list

### ISSUE THREAD

**Issue by edlee123** [jimhester/lintr#193]
e.g. nada in below:
```
cat('a = function(x) x^2', file ="assignment.R")
lint("assignment.R", linters = list(lintr::assignment_linter)) 
```
But this will work:
```
lint("assignment.R", linters = list(a = lintr::assignment_linter))
```

The relevant line 71: 
```
for (expr in source_expressions$expressions) {
        for (linter in names(linters)) {
```
https://github.com/jimhester/lintr/blob/master/R/lint.R#71

**Comment by russHyde** [comment]
This issue (and related issues) have been raised a couple of times. Most recently in https://github.com/jimhester/lintr/issues/351 . Closing this issue since it has been duplicated. Docs to be updated.

**Comment by edlee123** [comment]
Thank you
