### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by alex88** [jimhester/lintr#198]
When trying to install lintr as a dependency from other packages I get:

```
* installing *source* package ‘lintr’ ...
** package ‘lintr’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(name) : there is no package called ‘nlme’
Error in loadNamespace(name) : there is no package called ‘survival’
Error in loadNamespace(name) : there is no package called ‘boot’
Error in loadNamespace(name) : there is no package called ‘foreign’
Error in loadNamespace(name) : there is no package called ‘KernSmooth’
Error in loadNamespace(name) : there is no package called ‘rpart’
Error in loadNamespace(name) : there is no package called ‘class’
Error in loadNamespace(name) : there is no package called ‘spatial’
Error in loadNamespace(name) : there is no package called ‘mgcv’
```

is it because the dependencies are listed only in `objects_linter.R` and not in the package dependencies?

**Comment by jimhester** [comment]
Those are all recommended packages and should be installed be default in most R distributions.

If you are installing R from source you will need to run `tools/rsync-recommended` to download the recommended packages before running `configure && make && make install`.

**Comment by alex88** [comment]
Oh ok, I'm not installing R from source but I'm using R package from alpine linux for a docker image.
I'll install them manually before lintr to see if it works. Thanks
