### ISSUE TITLE
Confusing function and class names

### ISSUE THREAD

**Issue by jrnold** [jimhester/lintr#209]
The naming conventions of functions and classes are inconsistent and confusing. `Lint()` creates objects of class `lint`, while `lint()` returns a `lints` object from linting a file. It would be more consistent if `lint()` was renamed to `lint_file`, and `lint()` is a function used to create a `lint()` object. Alternatively, change the name of the class from `lint` to `Lint`.  However, I think that `lint_file` is more clear and consistent with `lint_package`.

**Comment by jimhester** [comment]
Upper case names for object constructors is a widespread convention across programming languages.

`lint()` is the primary function for this package and I find value in having the primary function short. (this was changed from your proposal in https://github.com/jimhester/lintr/commit/31c67e954ebcf554f2d00475fc913974937bdb02).

It could be argued that there should also be a `Lints()` S3 constructor however.

**Comment by jrnold** [comment]
Understood. It's definitely a convention across other programming languages, though in R it seems that using a "constructor" function with the same name as the class seems more common.  Sorry, I hadn't realized, that this was already discussed and considered.  What about naming the class `Lint` then?  A `Lints()` S3 constructor would be nice as well.
