### ISSUE TITLE
Export more functions

### ISSUE THREAD

**Issue by jrnold** [jimhester/lintr#210]
It would be useful to export more functions since many of the unexported functions used internally are practically necessary to write custom linters.

**Comment by fangly** [comment]
I agree. See also #178

**Comment by jimhester** [comment]
Sure, send a PR with the additional functions you would like exported, be sure to document them appropriately as well.

**Comment by jrnold** [comment]
Okay, will do.

**Comment by wlandau** [comment]
@jrnold Do you have a tentative list? I would like to include `ids_with_token()`.

**Comment by russHyde** [comment]
@jrnold could you confirm that the currently-exported functions are sufficient for you to write custom linters, please.

**Comment by jimhester** [comment]
I think all the necessary functions are now exported.
