### ISSUE TITLE
get_source_expressions() removes some tokens

### ISSUE THREAD

**Issue by fangly** [jimhester/lintr#215]
Linters like `todo_comment_linter` and `semicolon_terminator_linter()` (#214) are more complicated than could be because some tokens are omitted by `get_source_expressions()` (not available within `source_file$parsed_content`).

```R
# TODO 1
x <- 3 # TODO 2
foo <- function(x) { # TODO 3
  # TODO 4
  x * 2 # TODO 5
}
y <- foo(x) # TODO 6
# TODO 7
```
In this first example (above), only TODO 3-5 are returned as COMMENT tokens in `source_file$parsed_content`. 

```R
a <- 1; b <- 2;
foo <- function(a, b) {
  c <- a + b; cat(c);
}
```
In this second example, only the two semicolons within the function are returned as ';' tokens. The two first are missing.

Ideally, one would want to have all needed tokens exposed, and the overcomplicated linters simplified.

The variable `parsed_content` in `get_source_expression()` seems to contain all tokens, but later in the same function, variable `expressions` seems to have dropped some of them. This illustrates that the issue is likely in lintr.

**Comment by jimhester** [comment]
I think the easiest solution to this is to include the full parsed content (and xml parsed content) in the global expressions https://github.com/thomaskisler/scripts/blob/68f286726141a34ce6ef4817a2f5c1227a3e9f24/ranger.plot.data.tree.R.

Alternatively I have thought about removing the caching / breaking into top level expressions, it complicates the implementation quite a bit and has corner cases for some linters that are I believe nearly impossible to handle.

**Comment by jimhester** [comment]
Sorry forgot to copy the link properly, now fixed.

**Comment by fangly** [comment]
Pull request was merged, so closing this issue.
