### ISSUE TITLE
Correct syntax for linters option in lint()

### ISSUE THREAD

**Issue by blindjesse** [jimhester/lintr#224]
I'm trying to pass a list of linters I would like to use to `lint`. I cannot find the right syntax.

THis works:

    lint('aoi.R', linters=assignment_linter)
    aoi.R:8:13: style: Use <-, not =, for assignment.
    values(aoi) = 1
                ^

But not this (no output, seems to be the desired syntax though):

    lint('aoi.R', linters=list(assignment_linter))

This doesn't work either (multiple linters; no output):

    lint('aoi.R', linters=list(assignment_linter, single_quotes_linter))

But this does:

    lint('aoi.R', linters=list('assignment_linter'=assignment_linter, 'single_quotes_linter'=single_quotes_linter))
    aoi.R:3:8: style: Only use double-quotes. 
    source('code/constants.R')
           ^~~~~~~~~~~~~~~~~~
    aoi.R:8:13: style: Use <-, not =, for assignment.
    values(aoi) = 1
                ^

Is the last option correct? Seems a little long...

**Comment by jimhester** [comment]
lintr needs a named list, but will now automatically name any unnamed elements, so you can pass an unnamed list.
