### ISSUE TITLE
Auto lintr?

### ISSUE THREAD

**Issue by naught101** [jimhester/lintr#227]
Has anyone looked at implementing an automatic lint fixer for R? Something along the lines of [autopep8](https://github.com/pbrod/autopep8)? R really lends it self to writing untidy code, and so an automatic tool would be really useful. For example, it could be applied to multiple branches of a repo before merging to make merging much smoother.

I'm not sure how much work would be involved, but I guess a fair bit. I also guess there probably wouldn't be much code worth sharing with autopep8, but there might be some lessons to be learned from there. Perhaps @hhatto or @myint would be able to provide some insight?

**Comment by naught101** [comment]
Oh, I just found https://github.com/yihui/formatR, which probably covers most bases. Sorry for the noise.

**Comment by naught101** [comment]
Hrm.. except it does not deal very well with line breaks inside function calls (https://github.com/yihui/formatR/issues/53)...

**Comment by jimhester** [comment]
I have long wanted to extend lintr, or write a package which builds on lintr outputs to do reformatting / autocorrecting of lint results. There are some issues with the amount of informationHowever there are a few packages that give you some of this functionality.

- [formatR](https://github.com/yihui/formatR) - subject to caveats mentioned in that package.
- [rfmt](https://github.com/google/rfmt) - Novel layout algorithm which works quite well, however requires python to be installed and is not on CRAN.
- [styler](https://github.com/krlmlr/styler) - In development package by @krlmlr and @yihui, part of a google summer of code project, but could be what you are looking for once it is complete.
