### ISSUE TITLE
linting dplyr %>%?

### ISSUE THREAD

**Issue by dfrankow** [jimhester/lintr#229]
From

```
  df <- df %>% dplyr::mutate(frac.lcl = ci$lower, frac.ucl = ci$upper)
```

it warns `No visible global function definition for '%>%', Did you mean '%*%'?`

The lint message is true, yet I wish to use %>%. How do I turn off that lint message? I can't tell which rule it is. Or is there a better way to lint %>% ?

I could turn off the lint warning for just that line, but I did not understand this: "You can use a named item to exclude only certain lines from a file." Do I need to give the exact line number? What if the file changes?

**Comment by dfrankow** [comment]
Just saw this, I'm going to try it:

"With the following command, you can create a configuration file for lintr that ignores all linters that show at least one error: ..."

**Comment by dfrankow** [comment]
A friend had another comment: all the dplyr functions read much better without global prefixes. That is, it would look better if we could do

```
df <- df %>% mutate(frac.lcl = ci$lower, frac.ucl = ci$upper)
```

Thoughts?

**Comment by dfrankow** [comment]
Hmm, it appears if there is a newline after the `%>%` that sometimes makes it happy. Example:

```
df <- df %>%
  mutate(frac.lcl = ci$lower, frac.ucl = ci$upper)
```

If that's always true, I could live with it.

**Comment by fangly** [comment]
1. I believe your `No visible global function definition` lint is issued by the pretty generic `object_usage_linter()`.
2. The newline after `%>%` is addressed by the `pipe_continuation_linter()`. Its goal is to 

> Check that each step in a pipeline is on a new line, or the entire pipe fits on one line.
