### ISSUE TITLE
Trailing whitespace linter applies to pipe %>%?

### ISSUE THREAD

**Issue by dchiu911** [jimhester/lintr#231]
The RStudio shortcut for the pipe command `%>%` inserts a space after the last `%` sign. Hence we get a bunch of trailing whitespace lints if the user decided to line return *without* deleting that last space first. Is this the intended behaviour? What would be the preferable workflow when working with pipes?

**Comment by jimhester** [comment]
The RStudio IDE has a option to automatically strip trailing whitespace when saving, that is probably the easiest solution.

![screenshot 2017-04-27 07 07 20](https://cloud.githubusercontent.com/assets/205275/25480768/3f07dfb2-2b18-11e7-9956-d39cebd1ae5f.png)

**Comment by dchiu911** [comment]
When working within an R project, this option has to be applied to project-specific options:

![screen shot 2017-04-27 at 4 47 38 pm](https://cloud.githubusercontent.com/assets/8665632/25508770/45e7e68c-2b69-11e7-93f5-e1552231ce97.png)

The associated `.Rproj` file adds the line

```r
StripTrailingWhitespace: Yes
```
