### ISSUE TITLE
Allow sharing of .lintr files

### ISSUE THREAD

**Issue by dfrankow** [jimhester/lintr#238]
Thanks again for your work on lintr.

I have several projects in the same repo, and I want them to share the same .lintr configuration. Right now, I'm copying the .lintr files around, and it's unsatisfying.

All my projects are in the same directory. It would be enough for lintr to go up the tree seeking a .lintr file.

If you approve of that solution, I might try a pull request. I can see the file: https://github.com/jimhester/lintr/blob/5485cd14a13b7bd50733d9f9101a4a791c8a44e4/R/settings.R#L15.

**Comment by jimhester** [comment]
Yeah that sounds fine, just be sure the search starts at the project directory rather than the working directory.
