### ISSUE TITLE
Plain Code Blocks in RMarkdown

### ISSUE THREAD

**Issue by russHyde** [jimhester/lintr#252]
I have an issue when running lintr (v1.0.0 in vim or within R) on Rmarkdown files that contain plain code blocks (as defined [here](http://rmarkdown.rstudio.com/authoring_basics.html)). Running lintr on the following (temp.Rmd) throws an "Error: Malformed file!", despite plain code blocks being legal in Rmarkdown and lintr working fine on any other Rmarkdown files that contain R code. If the block containing "This isn't evaluated" is removed, lintr runs fine; when it's present, the Malformed file error comes up.

\---
title: "Plain Code Bug?"
output: pdf_document
\---
\```{r}
42
\```

\```
This isn't evaluated
\```

**Comment by sebastiansauer** [comment]
Similar for me; I get the same error. I have some non-R fenced blocks in my rmd-file, eg.,

```{block2, dplyr-no-brackets, type='rmdcaution', echo = TRUE} 
some text

```

(This code blocks are taken from bookdown)

**Comment by russHyde** [comment]
Disregard this issue; I now wrap plain-code-blocks in a "~~~~" block and the Malformed file bug doesn't come up in lintr (I couldn't pinpoint the problem within lintr or it's dependencies though)

```
~~~~
This isn't evaluated
~~~~
```

**Comment by randy3k** [comment]
I think we should keep this issue opened until it is probably addressed.

**Comment by russHyde** [comment]
Do you think this relates to the #322 bug whereby lintr parses non-R code blocks (eg, embedded bash / python) as if they were R code?

**Comment by randy3k** [comment]
It is a different bug. At least a python block doesn't throw `Malformed file`.

**Comment by russHyde** [comment]
I've submitted a PR to hopefully fix this.
