### ISSUE TITLE
todo_comment_linter seems to be ignoring comments

### ISSUE THREAD

**Issue by mjsteinbaugh** [jimhester/lintr#255]
Hi Jim,

The `todo_comment_linter` doesn't appear to be returning warnings in my packages for lines containing `# FIXME` or `# TODO`, as expected. I have `linters: with_defaults(todo_comment_linter)` set in my `.lintr` file and am running the latest build of lintr from GitHub.

**Comment by spascoe** [comment]
This linter is one that needs to be called, not referenced. 
 `linters: with_defaults(todo_comment_linter())`
instead of
`linters: with_defaults(todo_comment_linter)`

**Comment by mjsteinbaugh** [comment]
Perfect! That works for me now. Thanks.
