### ISSUE TITLE
invalid regular expression

### ISSUE THREAD

**Issue by ThierryO** [jimhester/lintr#257]
When running `lintr::lint_package()` I get the following error.

    Error in grep(pat, text) : invalid regular expression '(?<!(^|)``)`r[ #]([^`]+)\s*`', reason 'Invalid regexp' 

I get the same error with several packages. It used to run fine in the past and I didn't change the code of the packages. Below is the session info

    devtools::session_info("lintr")
    Session info ----------------------------------------------------------------------------------------
     setting  value                       
     version  R version 3.4.1 (2017-06-30)
     system   x86_64, linux-gnu           
     ui       RStudio (1.1.317)           
     language nl_BE:nl                    
     collate  nl_BE.UTF-8                 
     tz       Europe/Brussels             
     date     2017-07-28                  
    
    Packages --------------------------------------------------------------------------------------------
     package      * version    date       source                                   
     BH             1.62.0-1   2016-11-19 CRAN (R 3.4.0)                           
     codetools      0.2-15     2016-10-05 CRAN (R 3.3.1)                           
     compiler       3.4.1      2017-07-08 local                                    
     crayon         1.3.2      2016-06-28 CRAN (R 3.4.0)                           
     curl           2.7        2017-06-26 CRAN (R 3.4.1)                           
     digest         0.6.12     2017-01-27 CRAN (R 3.4.0)                           
     evaluate       0.10.1     2017-06-24 CRAN (R 3.4.1)                           
     graphics     * 3.4.1      2017-07-08 local                                    
     grDevices    * 3.4.1      2017-07-08 local                                    
     highr          0.6        2016-05-09 CRAN (R 3.4.0)                           
     httr           1.2.1      2016-07-03 CRAN (R 3.4.0)                           
     jsonlite       1.5        2017-06-01 cran (@1.5)                              
     knitr          1.16.5     2017-07-24 local                                    
     lazyeval       0.2.0      2016-06-12 CRAN (R 3.4.0)                           
     lintr        * 1.0.0.9001 2017-07-27 Github (jimhester/lintr@3312afa)         
     magrittr       1.5        2014-11-22 CRAN (R 3.4.0)                           
     markdown       0.8        2017-04-20 CRAN (R 3.4.0)                           
     methods      * 3.4.1      2017-07-08 local                                    
     mime           0.5        2016-07-07 CRAN (R 3.4.0)                           
     openssl        0.9.6      2016-12-31 CRAN (R 3.4.0)                           
     parallel       3.4.1      2017-07-08 local                                    
     praise         1.0.0      2015-08-11 CRAN (R 3.4.0)                           
     R6             2.2.2      2017-06-17 CRAN (R 3.4.0)                           
     Rcpp           0.12.12    2017-07-15 CRAN (R 3.4.1)                           
     rex            1.1.1      2016-12-05 CRAN (R 3.4.0)                           
     rstudioapi     0.6        2016-06-27 CRAN (R 3.4.0)                           
     stats        * 3.4.1      2017-07-08 local                                    
     stringdist     0.9.4.4    2016-12-16 CRAN (R 3.4.0)                           
     stringi        1.1.5      2017-04-07 CRAN (R 3.4.0)                           
     stringr        1.2.0      2017-02-18 CRAN (R 3.4.0)                           
     testthat       1.0.2      2016-04-23 CRAN (R 3.4.0)                           
     tools          3.4.1      2017-07-08 local                                    
     utils        * 3.4.1      2017-07-08 local                                    
     xml2           1.1.1      2017-07-27 Github (hadley/xml2@4be4590)             
     xmlparsedata   1.0.1      2017-07-27 Github (MangoTheCat/xmlparsedata@3377216)
     yaml           2.1.14     2016-11-12 CRAN (R 3.4.0)

**Comment by lbusett** [comment]
I get the same error: 

Session info ----------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, mingw32             
 ui       RStudio (1.1.306)           
 language (EN)                        
 collate  English_United Kingdom.1252 
 tz       Europe/Paris                
 date     2017-07-29                  

Packages --------------------------------------------------------------------------------------------------------------
 package      * version     date       source                                    
 assertthat     0.2.0       2017-04-11 CRAN (R 3.4.1)                            
 base         * 3.4.1       2017-06-30 local                                     
 bindr          0.1         2016-11-13 CRAN (R 3.4.0)                            
 bindrcpp       0.2         2017-06-17 CRAN (R 3.4.0)                            
 codetools      0.2-15      2016-10-05 CRAN (R 3.4.1)                            
 compiler       3.4.1       2017-06-30 local                                     
 crayon         1.3.2.9000  2017-07-25 Github (gaborcsardi/crayon@750190f)       
 data.table     1.10.4      2017-02-01 CRAN (R 3.4.0)                            
 datasets     * 3.4.1       2017-06-30 local                                     
 DBI            0.7         2017-06-18 CRAN (R 3.4.0)                            
 devtools     * 1.13.2.9000 2017-07-11 Github (hadley/devtools@d3482c5)          
 digest         0.6.12      2017-01-27 CRAN (R 3.4.0)                            
 doSNOW         1.0.14      2015-10-14 CRAN (R 3.4.0)                            
 dplyr          0.7.2       2017-07-20 CRAN (R 3.4.1)                            
 foreach        1.4.3       2015-10-13 CRAN (R 3.4.0)                            
 gdalUtils      2.0.1.7     2015-10-10 CRAN (R 3.4.1)                            
 glue           1.1.1.9000  2017-07-23 Github (tidyverse/glue@28aa740)           
 graphics     * 3.4.1       2017-06-30 local                                     
 grDevices    * 3.4.1       2017-06-30 local                                     
 grid           3.4.1       2017-06-30 local                                     
 hexbin         1.27.1      2016-12-05 CRAN (R 3.4.1)                            
 htmltools      0.3.6       2017-04-28 CRAN (R 3.4.0)                            
 httpuv         1.3.5       2017-07-04 CRAN (R 3.4.1)                            
 hunspell     * 2.6         2017-06-28 CRAN (R 3.4.1)                            
 iterators      1.0.8       2015-10-13 CRAN (R 3.4.0)                            
 knitr          1.16.6      2017-07-28 Github (yihui/knitr@cf86e6a)              
 lattice        0.20-35     2017-03-25 CRAN (R 3.4.1)                            
 latticeExtra   0.6-28      2016-02-09 CRAN (R 3.4.1)                            
 lazyeval       0.2.0       2016-06-12 CRAN (R 3.4.0)                            
 lbscripts    * 0.1.0.9000  2017-07-29 Github (lbusett/lbscripts@bf94fbe)        
 lintr        * 1.0.0       2016-04-16 CRAN (R 3.4.1)                            
 lubridate      1.6.0       2016-09-13 CRAN (R 3.4.0)                            
 magrittr       1.5         2014-11-22 CRAN (R 3.4.0)                            
 memoise        1.1.0       2017-04-21 CRAN (R 3.4.0)                            
 methods      * 3.4.1       2017-06-30 local                                     
 mime           0.5         2016-07-07 CRAN (R 3.4.0)                            
 miniUI         0.1.1       2016-01-15 CRAN (R 3.4.0)                            
 parallel       3.4.1       2017-06-30 local                                     
 pkgbuild       0.0.0.9000  2017-07-11 Github (r-pkgs/pkgbuild@8aab60b)          
 pkgconfig      2.0.1       2017-03-21 CRAN (R 3.4.0)                            
 pkgload        0.0.0.9000  2017-06-11 Github (r-pkgs/pkgload@119cf9a)           
 R.methodsS3    1.7.1       2016-02-16 CRAN (R 3.4.0)                            
 R.oo           1.21.0      2016-11-01 CRAN (R 3.4.0)                            
 R.utils        2.5.0       2016-11-07 CRAN (R 3.4.0)                            
 R6             2.2.2       2017-06-17 CRAN (R 3.4.0)                            
 raster       * 2.5-8       2016-06-02 CRAN (R 3.4.1)                            
 rasterVis      0.41        2016-12-10 CRAN (R 3.4.1)                            
 RColorBrewer   1.1-2       2014-12-07 CRAN (R 3.4.0)                            
 Rcpp           0.12.12     2017-07-15 CRAN (R 3.4.1)                            
 rex            1.1.1       2016-12-05 CRAN (R 3.4.0)                            
 rgdal          1.2-8       2017-07-01 CRAN (R 3.4.1)                            
 rgeos          0.3-23      2017-04-06 CRAN (R 3.4.1)                            
 rlang          0.1.1       2017-05-18 CRAN (R 3.4.0)                            
 rstudioapi     0.6         2016-06-27 CRAN (R 3.4.1)                            
 sf             0.5-2       2017-07-12 CRAN (R 3.4.1)                            
 shiny        * 1.0.3       2017-04-26 CRAN (R 3.4.0)                            
 sinew        * 0.3.0       2017-07-29 Github (metrumresearchgroup/sinew@cc363a5)
 snow           0.4-2       2016-10-14 CRAN (R 3.4.0)                            
 sp           * 1.2-5       2017-06-29 CRAN (R 3.4.1)                            
 sprawl       * 0.1.0.9000  2017-07-29 local                                     
 sprawl.data  * 0.0.0.9000  2017-07-15 Github (lbusett/sprawl.data@9740d69)      
 stats        * 3.4.1       2017-06-30 local                                     
 stringi        1.1.5       2017-04-07 CRAN (R 3.4.0)                            
 stringr        1.2.0       2017-02-18 CRAN (R 3.4.0)                            
 testthat     * 1.0.2.9000  2017-07-11 Github (hadley/testthat@c7e8330)          
 tibble         1.3.3       2017-05-28 CRAN (R 3.4.0)                            
 tidyr          0.6.3       2017-05-15 CRAN (R 3.4.0)                            
 tools          3.4.1       2017-06-30 local                                     
 udunits2       0.13        2016-11-17 CRAN (R 3.4.0)                            
 units          0.4-5       2017-06-15 CRAN (R 3.4.0)                            
 utils        * 3.4.1       2017-06-30 local                                     
 velox          0.1.0       2016-08-25 CRAN (R 3.4.1)                            
 viridisLite    0.2.0       2017-03-24 CRAN (R 3.4.1)                            
 withr          1.0.2       2016-06-20 CRAN (R 3.4.0)                            
 xtable         1.8-2       2016-02-05 CRAN (R 3.4.0)                            
 yaml           2.1.14      2016-11-12 CRAN (R 3.4.0)                            
 zoo            1.8-0       2017-04-12 CRAN (R 3.4.0)

**Comment by mplough** [comment]
Updating to lintr version 1.0.1 appears to fix this issue.

**Comment by jimhester** [comment]
Yes it is fixed by lintr 1.0.1.
