### ISSUE TITLE
'fun' not found

### ISSUE THREAD

**Issue by tristanwietsma** [jimhester/lintr#26]
Transitioning from #25 to narrower scope:

``` R
> lint('EngineXLSX.R', with_defaults(line_length_linter(80)))
Error in body(fun) : object 'fun' not found
```

Source does execute without a hitch.

**Comment by jimhester** [comment]
@tristanwietsma sorry I haven't gotten to the bottom of this yet, probably just need to tweak the `try(fun <- eval(parse(text = text, keep.source = TRUE), 
               envir = env), silent = TRUE)` logic only execute the subsequent lines if the eval line succeeds.

**Comment by tristanwietsma** [comment]
thanks. let me know if you need me to test a branch.

**Comment by hampei** [comment]
I'm running into this as well. 
Can't use the linter because of it. Anyone found a solution/workaround?

**Comment by etheleon** [comment]
+1
