### ISSUE TITLE
How to enable lintr in RStudio?

### ISSUE THREAD

**Issue by jcubic** [jimhester/lintr#261]
I have RStudio 1.0.153 and I don't have Markers pane how to enable it I only have console. I've search but couldn't find how to enable this.

**Comment by jcubic** [comment]
Ok, found it Menu: Code > Show Diagnostics

**Comment by jimhester** [comment]
To be clear the diagnostics in RStudio are not powered by lintr, they are a separate code base.

**Comment by jcubic** [comment]
Oh, just found your project and README say it's enabled by default in RStudio. It seems that lintr find more issue with the code, is there a way to enable it in RStudio or only Diagnostic.

**Comment by jimhester** [comment]
You just need to run `lintr::lint()` or `lintr::lint_packge()` in the console, there is no way I am aware of to do it automatically.

**Comment by alessandro-gentilini** [comment]
I had exactly the same problem as @jcubic
