### ISSUE TITLE
Add ALE to the README if you want

### ISSUE THREAD

**Issue by w0rp** [jimhester/lintr#263]
My plugin supports running lintr in Vim while you type. I was just merging a pull request now for making the lintr options configurable, and I thought I'd let you know. [ALE](https://github.com/w0rp/ale) has become pretty popular, so you could mention it if you want.

**Comment by jimhester** [comment]
I don't use ALE, what do users have to do to enable lintr using it, anything other than have the lintr package installed?

**Comment by StefanBRas** [comment]
It will be enabled by default for .R files. I can make a pull request to add it to the README.md shortly. 

However it does not support the use of ".lintr" config files (see [this issue](https://github.com/dense-analysis/ale/issues/824) in the ALE repository), which is related to #123.

**Comment by russHyde** [comment]
ALE is in the README now file:///android_asset/md/#vim---ale  . Closing
