### ISSUE TITLE
Neovim

### ISSUE THREAD

**Issue by rpietro** [jimhester/lintr#276]
Hi @jimhester , just wondering if you had any tips installing lintr to neovim. Syntastic is not supported on neovim, and the lintr installation doesn't seem to be working

thanks

**Comment by jimhester** [comment]
I use neovim myself and for a long time with Syntastic, did you try it and failed?

**Comment by jimhester** [comment]
You might try using https://github.com/w0rp/ale, which now supports lintr out of the box and does the linting asynchronously.
