### ISSUE TITLE
Unable to install lintr on CentOS6 

### ISSUE THREAD

**Issue by aksh7860** [jimhester/lintr#277]
gcc -m64 -std=gnu99 -shared -L/usr/lib64/R/lib -o irlba.so irlb.o utility.o -L/usr/lib64/R/lib -lRlapack -L/usr/lib64/R/lib -lRblas -lgfortran -lm -L/usr/lib64/R/lib -lR
/usr/bin/ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status
make: *** [irlba.so] Error 1
ERROR: compilation failed for package 'irlba'
* removing '/home/abkumar/R/x86_64-redhat-linux-gnu-library/3.4/irlba'
ERROR: dependency 'irlba' is not available for package 'igraph'
* removing '/home/abkumar/R/x86_64-redhat-linux-gnu-library/3.4/igraph'
ERROR: dependency 'igraph' is not available for package 'lintr'
* removing '/home/abkumar/R/x86_64-redhat-linux-gnu-library/3.4/lintr'

The downloaded source packages are in
        '/tmp/Rtmphlxuhg/downloaded_packages'
Warning messages:
1: In download.file(url, destfile = f, quiet = TRUE) :
  URL 'https://cran.r-project.org/CRAN_mirrors.csv': status was 'Couldn't connect to server'
2: In install.packages("lintr") :
  installation of package 'irlba' had non-zero exit status
3: In install.packages("lintr") :
  installation of package 'igraph' had non-zero exit status
4: In install.packages("lintr") :
  installation of package 'lintr' had non-zero exit status

**Comment by gaborcsardi** [comment]
Because you can't install `irlba`. And that's because you don't have a fortran library. Seems like you need the `libgfortran` RPM package, install it with `yum`.

**Comment by aksh7860** [comment]
Wow ,that was fast.Thank you for replying so fast.Actually their is another query how can we use lintr to run through command line on a particular R file and save the warnings in a file instead of running it on console

**Comment by aksh7860** [comment]
I m closing this issue and starting a new thread to ask my question
