### ISSUE TITLE
RStudio addins missing from CRAN

### ISSUE THREAD

**Issue by ha0ye** [jimhester/lintr#280]
Not sure if this is a bug or maybe a CRAN restriction, but seems like the 1.0.2 release on CRAN is missing the /inst/rstudio/addins.dcf file.

Was scratching my head for a while over why the lintr addins weren't showing up, and then ended up  just installing from GitHub...

**Comment by ha0ye** [comment]
Actually, having some trouble with the "Lint current file" addin. Seems to break if there isn't a config file:

```
config_file <- lintr:::find_config(filename$path)
config <- read.dcf(config_file, all = T)
```

I think this is an easy fix by adding in a null check earlier and then moving to using the `default_linters`. Let me know if a PR would be helpful.

**Comment by jimhester** [comment]
The lintr addins are not in the CRAN release, 1.0.2 was a patch fix for a testthat incompatibility, it does not contain any new features from 1.0.1.

Sure if you could submit a PR that would be great!
