### ISSUE TITLE
trailingwhitespace linter to accept argument n to ignore n blank line 

### ISSUE THREAD

**Issue by BenoitLondon** [jimhester/lintr#284]
so like n=1 would flag two consecutive blank lines and so on..,  maybe 0 as default as the current behavior

**Comment by jimhester** [comment]
Why would you want any blank lines at the end of your file?

**Comment by BenoitLondon** [comment]
Not at the end, lintr complains about blank lines in code sometimes.

**Comment by jimhester** [comment]
It should not, do you have an example?

**Comment by BenoitLondon** [comment]
Ok I finally found why :)
Rstudio automatically inserts 4 whitespaces when pressing enter to jump a line hence the lintr gets triggered. but if it 's a pure blank line (no space) it doesn't complain.
maybe it s an issue for rstudio then? to delete white spaces in blank line as they do for trailing whitespaces when saving.

**Comment by BenoitLondon** [comment]
oh actually it does it with the new option... sorry for taking your time
