### ISSUE TITLE
FileName not being displayed when running no_tab_linter 

### ISSUE THREAD

**Issue by apandit24** [jimhester/lintr#285]
When i am running no_tab_linter on a file errors are being displayed but without filename

src <- get_source_expressions(filename)
no_tab_linter(src)

o/p

[[6]]
[[6]][[1]]
:6:36: style: Use two spaces to indent, never tabs.
        doors[mask] <- !doors[mask]
                                   ^
The filename is missing before :6

And Also i m seeing that where ever source$filename is used in code all those linters are not working such as assignment_linter, no_tab_linter but when using lint function it is giving correct o/p because their file name is explicitly sent as argument to lint function.

Please help me in this ...

**Comment by jimhester** [comment]
You should be using `lintr::lint(filename, linters = lintr::no_tab_linter)` to lint a single file, I am not sure why you are using the unexported get_source_expressions function directly.
