### ISSUE TITLE
lintr not working with flycheck

### ISSUE THREAD

**Issue by arnyeinstein** [jimhester/lintr#289]
Hi
lintr is working fine in Emacs 25.3.1 for Windows from the command line (e.g. lint('myfile.R'). However, if I run it by activating flycheck, there is an issue with the path to rterm.exe:

> Suspicious state from syntax checker r-lintr: Flycheck checker r-lintr returned non-zero exit code 1, but its output contained no errors: 'c:\PROGRA~1\R\R-34~1.3/bin/x64/Rterm.exe" --slave --restore --no-save -e "library' is not recognized as an internal or external command,
operable program or batch file.

The path is not correct. I added the following line to my .emacs, but this didn't change a thing:

> (setq inferior-R-program-name "C:/Program Files/R/R-3.4.3/bin/x64/Rterm.exe")

I checked the windows registry and the path to Rterm is everywhere correct and not as in the error message in Emacs. I reinstalled flycheck and ess, but that also didn't solve the problem. lintr is working correctly in my RStudio.

Running flycheck-verify-checker gives me

Syntax checker in buffer unif.R in ess-mode:

```
  r-lintr
    - major mode:    `ess-mode' supported
    - may enable:    yes
    - predicate:     t
    - executable:    Found at C:/Program Files/R/R-3.4.3/bin/x64/R.exe
    - lintr library: present

Flycheck can use this syntax checker for this buffer.
Flycheck Mode is disabled.  Use C-u M-x flycheck-disable-checker to enable
disabled checkers.
--------------------
Flycheck version: 32snapshot (package: 20171214.1215)
Emacs version:    25.3.1
System:           x86_64-w64-mingw32
Window system:    w32
```

Any idea what is going wrong?

Cheers
Renger

**Comment by AdamCottrill** [comment]
This is looks like a flycheck issue and was addressed here: https://github.com/flycheck/flycheck/issues/1374.  

Adam
