### ISSUE TITLE
with_defaults docs bug

### ISSUE THREAD

**Issue by michaellevy** [jimhester/lintr#292]
I believe this enforces snake case and not camel case.

```
# enforce camelCase rather than snake_case
with_defaults(camel_case_linter = NULL,
              snake_case_linter)
```

**Comment by jimhester** [comment]
No, the snake_case_linter lints snake case variables, the camel_case_linter lints camel case variables. So if you want to use camel case variables you need to turn in the snake case longer.

**Comment by michaellevy** [comment]
Right, to enforce X means people must do X. Thanks.
