### ISSUE TITLE
Allow `##` in commented_code_linter?

### ISSUE THREAD

**Issue by prosoitos** [jimhester/lintr#299]
In emacs ESS, `##` starts a commented line, while `#` starts a comment at the end of a code line. This is convenient for auto-indentation (`## comments` do not indent, while `# comments` automatically indent).

Lintr considers `##` to start a comment as a mistake. Would it create other issues down the line to add `##` to the commented_code_linter?

**Comment by jimhester** [comment]
I am fine with changing this, would be happy to accept a PR for it!

**Comment by prosoitos** [comment]
Great!

I just gave it a try. This is my very first PR, so please bear with me if I messed something up...
