### ISSUE TITLE
infix operators don't conform to tidyverse standards

### ISSUE THREAD

**Issue by nathaneastwood** [jimhester/lintr#302]
I have found a difference between `lintr` and [`styler`](https://github.com/r-lib/styler). `styler` will correct the following

```r
(10 ^ (x - 1)) + 1
```

to

```r
(10^(x - 1)) + 1
```

This gives the following `lintr` errors:

```
Put spaces around all infix operators.
Place a space before left parenthesis, except in a function call.
```

Looking at the current tidyverse style guide, [`styler` is correct here](http://style.tidyverse.org/syntax.html#spacing). To get around this you can use

```r
styler::style_pkg(".", math_token_spacing = list(one = c("'^'", "'+'", "'-'", "'*'", "'/'")))
```

A similar issue exists with

```r
break ()
```

which gets corrected to 

```r
break()
```

by `styler`. I am not sure which is correct with regards to the tidyverse here.

**Comment by jimhester** [comment]
The `^` behavior is a bug, PR are welcome.

`break` is a statement, not a function call, so you should not have `()` in your code at all in this case.

**Comment by tvatter** [comment]
Quick question: I noticed that this fix is not present on the CRAN version, which is around 6 months more recent than the fix itself. Any idea what happened?

**Comment by bersbersbers** [comment]
Hello, I believe this is still an issue:
```x^(y + z)```

lintr still says 

> Place a space before left parenthesis, except in a function call.
