### ISSUE TITLE
enforce camelCase only in R code not in test folders

### ISSUE THREAD

**Issue by LiNk-NY** [jimhester/lintr#305]
Hi Jim! @jimhester 

It would be good to remove any checks in the test folders when using the `snake_case_linter`.
Perhaps this could be an argument to the function?
This would apply when developing a `Bioconductor` package and using `testthat` for testing. 

Regards,
Marcel

**Comment by russHyde** [comment]
This directory can now be excluded from linting using `exclusions: "tests"` in the .lintr config. Closing
