### ISSUE TITLE
SQALE Rating from Lintr

### ISSUE THREAD

**Issue by davidtam28** [jimhester/lintr#307]
Hello this is a question rather than issue - is it possible to generate SQALE rating (or Maintainability Rating in sonarqube speak) out of the lintr result?  I couldnt find anything in the document and I suspect this is not available.  In that case what is the process of making it a feature request?

Thank you in advance!

**Comment by jimhester** [comment]
No, I have never heard of SQUALE rating before. From a quick search it looks like someone would have to write a new package to compute this metric (possibly using lintr and other packages).

It does not seem appropriate to add it to lintr itself
