### ISSUE TITLE
Missing from RStudio's addin list

### ISSUE THREAD

**Issue by EndenDragon** [jimhester/lintr#310]
Hello, I just installed lintr in my RStudio via `install.packages("lintr")`. However, when I checked the addin dropdown in RStudio, it is missing lintr options. What went wrong with my lintr installation?

**Comment by jbhoosreddy** [comment]
I also don't see it in the addin list in RStudio.

But I also don't see the Markers pane after following the README, so I dunno.

**Comment by jimhester** [comment]
Nothing is wrong, the addin is only included with the development version of lintr

```r
devtools::install_github("jimhester/lintr")
```

**Comment by EndenDragon** [comment]
Perfect! Thank you so much for the help!

**Comment by espinielli** [comment]
Maybe it is worth mentioning this in the README...until it eventually lands in a CRAN version
(I spent quite some time to try to understand what I was doing wrong with the installation... ;-)
