### ISSUE TITLE
Error in vapply(eq_assign_locs, next_with_parent, pc = pc, integer(1)) :

### ISSUE THREAD

**Issue by cwhoffmannch** [jimhester/lintr#312]
Trying to lint my package:
sink("Lint_cwhmisc.R");datetime();lint_package("/Users/hoffmannc/R/cwhmisc/R");datetime();sink()
I get:
................Error in vapply(eq_assign_locs, next_with_parent, pc = pc, integer(1)) : 
  values must be length 1,
 but FUN(X[[1]]) result is length 0
There is no indication of the location where the errors was thrown.
This type of linting has been successful not so many days ago, so I am mystified.

**Comment by cwhoffmannch** [comment]
traceback()
13: vapply(eq_assign_locs, next_with_parent, pc = pc, integer(1))
12: fix_eq_assign(adjust_columns(getParseData(source_file)))
11: get_source_file(source_file, error = lint_error)
10: get_source_expressions(filename)
9: lint(file, ..., parse_settings = FALSE)
8: FUN(X[[i]], ...)
7: lapply(files, function(file) {
       if (interactive()) {
           message(".", appendLF = FALSE)
       }
       lint(file, ..., parse_settings = FALSE)
   })
6: inherits(x, class)
5: assign_item(x)
4: flatten_list(x, class = "lint")
3: structure(flatten_list(x, class = "lint"), class = "lints")
2: flatten_lints(lapply(files, function(file) {
       if (interactive()) {
           message(".", appendLF = FALSE)
       }
       lint(file, ..., parse_settings = FALSE)
   }))
1: lint_package("/Users/hoffmannc/R/cwhmisc/R")

**Comment by cwhoffmannch** [comment]
What can I learn from this?

**Comment by josiekre** [comment]
I'm getting this error on a variety of files as well that `styler` already linted. Not all of the files it linted create this error though.

**Comment by wjtimmerman** [comment]
For anyone reading this later, I ran into a similar error when I had mistyped a function argument in a script, ala 
`file = file = file.path(...` etc. Not sure if this is the OP's issue, but might solve yours.
