### ISSUE TITLE
vim lintr check slow

### ISSUE THREAD

**Issue by smilesun** [jimhester/lintr#314]
configuration is below
```
let g:syntastic_enable_r_lintr_checker = 1
let g:syntastic_r_checkers = ['lintr']
```
each type i type `w` in vim command mode, vim will be blocked and after a few seconds, the check results occur. Am i doing something wrong that the lintr works so slow with vim ?

**Comment by jimhester** [comment]
No, you can use https://github.com/w0rp/ale if you want the checks to run asynchronously.

**Comment by smilesun** [comment]
but ale is conflicting with syntastic, should I just supress the warning or remove syntastic. But how about 
```
let g:syntastic_enable_r_lintr_checker = 1
let g:syntastic_r_checkers = ['lintr']
```

**Comment by smilesun** [comment]
I mean the equivalent setting in ale. But maybe their github is the best place to ask this question.
