### ISSUE TITLE
Help collaborate on lintr!

### ISSUE THREAD

**Issue by jimhester** [jimhester/lintr#318]
As announced at https://twitter.com/jimhester_/status/997109466674819074 I am interested in having some help working on lintr. This issue can serve as a place for those interested to 'sign up' and also to discuss priorities. So reply below if you are interested and I will invite you to be a collaborator on the project.

**Comment by brankokovac** [comment]
Branko Kovac

**Comment by Jamesguy0121** [comment]
I am interested in helping out.

**Comment by jimhester** [comment]
So do you all think it would be helpful to have a [gitter](https://gitter.im) chat room so you could have more real time access for questions etc, or are GitHub comments enough?

**Comment by erleholgersen** [comment]
I'm also interested in helping out.

**Comment by navdeep-G** [comment]
I am interested if there is still room. :)

**Comment by adanvr** [comment]
I would like to help as well

**Comment by dougmet** [comment]
Hi, a few of us from Mango might be able to muck in as it slots together quite well with mangothecat/goodpractice and friends. cc @hfrick @sellorm

**Comment by jimhester** [comment]
@dougmet, that would be great, If the other Mango folks are interested please add a separate reply and I can add you to the collaborators.

**Comment by jimhester** [comment]
Also most of the linters in goodpractice that would be great to have in lintr, so a good first contribution would be doing that!

**Comment by wligtenberg** [comment]
I am interested in helping out as well.

**Comment by randy3k** [comment]
I am the author of https://github.com/REditorSupport/languageserver
I’d also like to be a collaborator.

**Comment by hfrick** [comment]
Hi @jimhester, some lintr/goodpractice crossover would be nice. 👋

**Comment by chucheria** [comment]
I want to help too! 🙌

**Comment by owenjonesuob** [comment]
Hiya, great to see interest in lintr-goodpractice collaboration! I'm definitely keen to help out.

**Comment by jimhester** [comment]
Never too late!

**Comment by DragosMG** [comment]
Same here. I'd be keen to help.

**Comment by cryptomanic** [comment]
I would love to contribute.

**Comment by gu-stat** [comment]
I'd like to help, if there's still room.

**Comment by jimhester** [comment]
A great first issue PR for someone to review would be https://github.com/jimhester/lintr/pull/321, it mainly needs a note added to NEWS.md

**Comment by gdequeiroz** [comment]
Hi @jimhester, what do you mean by "assess performance" in  `Assess performance of the devel version vs that of the current CRAN version (devel is quite a bit slower)`

**Comment by jimhester** [comment]
It would be great for someone to review https://github.com/jimhester/lintr/pull/326

**Comment by jabranham** [comment]
We can measure the speed difference between various linters by looping over the defaults:

```R
library(lintr)
x <- list(length = length(names(lintr::default_linters)))
i <- 1
for (name in lintr::default_linters){
  x[[i]] <- system.time(
    lint("check.R",
         linters = name,
         cache = FALSE))
  names(x)[i] <- names(lintr::default_linters[i])
  i <- i + 1
}
```

comparing the CRAN and github versions I get the following speeds:

```
                                   CRAN      GH
assignment_linter                 6.796   7.905
single_quotes_linter              7.633   8.772
absolute_paths_linter             9.637      NA
no_tab_linter                     8.007   9.637
line_length_linter                6.743   7.937
commas_linter                     8.745  10.155
infix_spaces_linter               8.687   9.975
spaces_left_parentheses_linter    9.251  10.608
spaces_inside_linter              7.862   9.471
open_curly_linter                 7.107   8.612
closed_curly_linter               7.077   8.572
camel_case_linter                33.693      NA
multiple_dots_linter              9.081      NA
object_length_linter              8.342 196.771
object_usage_linter              11.742  13.594
trailing_whitespace_linter        8.132   9.175
trailing_blank_lines_linter       6.588   7.903
commented_code_linter             8.349   8.495
function_left_parentheses_linter     NA  10.796
object_name_linter                   NA 196.275
pipe_continuation_linter             NA  75.777
```

So it looks to me that the two linters responsible for the slowdown are `object_name_linter` and `object_length_linter`. Those could just be removed from the defaults, if a CRAN release is planned soon.

**Comment by russHyde** [comment]
Happy to pitch-in if you still need helpers.
Russ Hyde, Glasgow Uni.

**Comment by Neil-Schneider** [comment]
Hi Jim, I would love to join the team.

**Comment by mjsteinbaugh** [comment]
@jimhester I'm up for adding some linters that help adhere to the [Bioconductor coding style](https://bioconductor.org/developers/how-to/coding-style/).

Also, is there an easy way to get S3 methods to pass linter checks (e.g. `function.default` will warn about the period).

**Comment by jameslamb** [comment]
As far as I could tell from #348 , this is the place to kindly request a new release to CRAN. The discussion on #348 predates [v1.0.3](https://cran.r-project.org/web/packages/lintr/index.html), which was released in November 2018.

Could you please prepare another release to CRAN?

I'd like to take advantage of these linters in projects that require building from package managers (not GitHub):

```r
github_only_linters <- list(
    "equals_na" = lintr::equals_na_linter
    , "function_left" = lintr::function_left_parentheses_linter
    , "implicit_integers" = lintr::implicit_integer_linter
    , "paren_brace_linter" = lintr::paren_brace_linter
    , "semiconlon" = lintr::semicolon_terminator_linter
    , "seq" = lintr::seq_linter
    , "todo_comments" = lintr::todo_comment_linter
    , "true_false" = lintr::T_and_F_symbol_linter
)
```

Thanks very much!

**Comment by joaopmatias** [comment]
Hi, I'd like to contribute, too!

**Comment by renkun-ken** [comment]
I'd like to contribute more, thanks!

**Comment by MichaelChirico** [comment]
I think this is safe to close; feel free to re-open
