### ISSUE TITLE
Lint r code from knitr documents

### ISSUE THREAD

**Issue by jimhester** [jimhester/lintr#32]
We should be able to lint R code from knitr documents.  Just have to be careful to check if `engine="r"` or no engine specified.

**Comment by maxheld83** [comment]
+1

**Comment by jimhester** [comment]
This is done as of 50ab86db4ebc7272d95990f8d15b3fabe0278936

**Comment by maxheld83** [comment]
great, thanks @jimhester 
lintr works fine in ST3 on `*.R`, though I can't get them to work on `*.Rnw`, `*.Rmd` yet.
Might be an issue with https://github.com/jimhester/SublimeLinter-contrib-lintr/issues as per https://github.com/jimhester/SublimeLinter-contrib-lintr/issues/5

Will ask StackExchange and report back.
