### ISSUE TITLE
lintr shiny app

### ISSUE THREAD

**Issue by ginberg** [jimhester/lintr#323]
I noticed it's possible to check a package with lint_package. I am developing many shiny applications and many times not part of a package.
It would be convenient if I could check the app with a single call like lint_shinyapp(<dirname>), something like this is not existing yet?  Looking forward to your thoughts about this.

**Comment by gu-stat** [comment]
You can check a regular R file using lint("file_name.R"), so it's not just for packages. 

On the other hand, lintr does not recognize some of Shiny function names. So if you run lint("app.R") you will get some unwanted warnings. I'll take a look at that.

**Comment by ginberg** [comment]
thanks @gu-stat for looking into this. 

Yes, I saw the lint() method to check a single file, but the single shiny app file approach is only used for small apps. In my experience, most apps use the server.R/ui.R approach and nowadays with the [modularization](https://shiny.rstudio.com/articles/modules.html) of apps, it's quite common that an app contains 5-10 R files, possibly in different sub-dirs.
So, I thought it would be convenient to have a method to scan all these files.

**Comment by jimhester** [comment]
Alternatively we could alter `lint()` to work on all projects, not just packages, e.g. https://github.com/jimhester/lintr/issues/217

**Comment by ginberg** [comment]
@jimhester yes, that could work indeed. 
Though it could be that the shiny app is a subdir of the project dir and all other files in the project are 'exploration code', so in that case it would be handy to supply a directory to check only the files that you want to have checked. Makes sense?

**Comment by jimhester** [comment]
We now have `lint_dir()`, which you could use in a shiny app, which I think addresses the primary concerns, so I will close this.
