### ISSUE TITLE
Make object_length_linter consistent accross

### ISSUE THREAD

**Issue by gdequeiroz** [jimhester/lintr#325]
It looks like the default argument for the`object_length_linter` function is 20: 
https://github.com/jimhester/lintr/blob/3312afafafd673aa7ec74231b39d83038508023c/R/object_name_linters.R#L182

but the default for calling it is 30: 
https://github.com/jimhester/lintr/blob/87658ec425ca5cb2c733444ab6beef45dbb31cfe/R/zzz.R#L96

It makes sense to make them consistent, so we should change the default argument to 30.

**Comment by DragosMG** [comment]
I think this issue can be closed. Thanks @gdequeiroz for the _good first issue_ label and thanks @jimhester for reviewing and approving my PR.
