### ISSUE TITLE
Warning message: In readLines(filename) : incomplete final line found on 'test.R'

### ISSUE THREAD

**Issue by Agent-Sesame** [jimhester/lintr#327]
Getting above error message when linting a very simple chunk of code. 

`runtimetool <- function(x) {

  start_time <- Sys.time()
  Sys.sleep(x)
  end_time <- Sys.time()
  time_taken <- end_time - start_time
  return(time_taken)

}`

**Comment by Agent-Sesame** [comment]
Thanks, that worked. Sorry for reporting such a minor thing~

**Comment by jimhester** [comment]
No worries, it is a little confusing, unfortunately the error message is coming from `readLines()` in this case, so there isn't a lot we can do in lintr

**Comment by gitmexanism** [comment]
Hello!
Have the same problem, but turning on the option didn't help(

Full message is:

Warning message: 
In readLines(con <- gzfile(tmp)): incomplete final line found on 'C:\Users\User\AppData\Local\Temp\RtmpWyvSp7\file2e042d652733'

**Comment by russHyde** [comment]
@gitmexanism I think that option only appends to files that have been modified since they were last saved. Could you add a newline and retry linting it, please.

**Comment by AraujoH** [comment]
If you use readr::read_lines(), that missing newline won'be be an issue.

**Comment by AshesITR** [comment]
Since #562 we actually catch this warning. One could create a `terminal_newline_linter` from this information if deemed useful?
