### ISSUE TITLE
Allow the user to pass the path of .lintr to lint()

### ISSUE THREAD

**Issue by mattiaciollaro** [jimhester/lintr#335]
Hey @jimhester, thanks again for this package!

I am trying to wrap `lintr`, together with linters for other languages, in [another project](https://github.com/spreemohealth/style).

Is it possible to manually pass the `.lintr` config file to `lint()` instead of having `lint()` look for it automatically in `current_dir -> project_dir -> user_dir` as implemented in the [`find_config`](https://github.com/jimhester/lintr/blob/89ec4178e6e76d94894cd97b31aa5b6a1a32c39e/R/settings.R#L52) function of the `settings.R` file?

I am currently trying to hack a temporary solution, because I think the answer to my question is *not at the moment*.
If it is in fact not possible to do so at the moment, do you think this could be made a feature?

I am thinking about the possibility of adding a `config_file` argument to `lint()` which, if not `NULL`, overrides the automatic search for the `.lintr` file (assuming that `parse_settings = TRUE`).

**Comment by jimhester** [comment]
The config file location is looked up by the R option `lintr.linter_file`, so you could use that to change the location. But I agree it should probably just be an argument to `lint()`.

**Comment by jimhester** [comment]
I think this was addressed with baddc5b
