### ISSUE TITLE
elpa availability

### ISSUE THREAD

**Issue by holocronweaver** [jimhester/lintr#34]
It is unclear if this package is available on elpa or any other Emacs package repository. It would make downloading and maintaining the latest version easier and more convenient.

**Comment by jimhester** [comment]
the emacs script is now integrated into flycheck as one of the [supported languages](http://www.flycheck.org/en/latest/guide/languages.html#r).  Flycheck should be available from Melpa or Melpa-Stable.

So you no longer need to track this repository for updates to the emacs flycheck script.  However updates to the R code still located here.
