### ISSUE TITLE
lintr-bot does not seem to respect `.lintr` file

### ISSUE THREAD

**Issue by javierluraschi** [jimhester/lintr#345]
See https://github.com/rstudio/mlflow/blob/master/R/mlflow/.lintr changing to line-width to 120 but comments in PR point to 80:

https://github.com/rstudio/mlflow/pull/43

**Comment by alexeckert** [comment]
I'm experiencing the same problem. The rules defined in a `.lintr` file will be respected when calling `lint_package` from RStudio or when calling it locally using `Rscript -e "lintr::lint_package()"`. In travis however all rules are used and `.lintr` won't be used.

**Comment by strboul** [comment]
I also experience the same problem.

**Comment by russHyde** [comment]
@javierluraschi I noted that you are using a testthat linting test. Could you confirm if you get the same problem if you remove the testthat call to linting and add an `after_success`  call to `Rscript -e 'lintr::lint_package()'` as described here https://github.com/jimhester/lintr#non-failing-lints
