### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by Fablepongiste** [jimhester/lintr#348]
Not really an issue to be fair but ... 

The current development version contains a lot of bug fixes and improvement. 
When will it be released on CRAN ?

**Comment by Fablepongiste** [comment]
Do you one day plan to release ? 
You have done such a nice package and lot of fixes but not releasing it ?

**Comment by jimhester** [comment]
See https://github.com/jimhester/lintr/issues/318#issuecomment-389972589, if you would like a CRAN release there are things which need to be addressed, we would be happy for your help.

**Comment by Fablepongiste** [comment]
Do you have list of issues preventing a CRAN release ?

Le ven. 12 oct. 2018 à 15:43, Jim Hester <notifications@github.com> a
écrit :
