### ISSUE TITLE
Possible to have a global .lintr file?

### ISSUE THREAD

**Issue by Hong-Revo** [jimhester/lintr#375]
As I understand it, lintr currently supports configuring on a per-project/directory basis. You put a `.lintr` file in the directory of a project, and the settings will apply within that project.

Is it possible to have a global `.lintr` file at all? I might be working on multiple projects but they all have the same style. It would be much easier just to apply a single file to every project, rather than having multiple files and the possibility that they get out of sync.

**Comment by Hong-Revo** [comment]
Ok, this is very confusing... according to c392b00ca41cafcd24576f7b40eba4533fd8339a, which was committed to master back in late 2017, this should already be possible. But the CRAN version of lintr, which dates to late 2018, doesn't have this change.

**Comment by Hong-Revo** [comment]
@randy3k

**Comment by randy3k** [comment]
You are right, the commit was merged to the dev branch but it has not yet appear in the production branch.

**Comment by Hong-Revo** [comment]
@russHyde would you be able to shed some light on this?

**Comment by russHyde** [comment]
Hi, I'm only a minor contributor to lintr. @jimhester will have a better idea re the release plans for the repo

**Comment by jimhester** [comment]
I will close this as it is fixed in the devel branch. Until recently the devel branch had serious performance regressions which prevented us doing any releases from it. Perhaps we can consider a release from it soon however.
