### ISSUE TITLE
dealing with the curly-curly operator

### ISSUE THREAD

**Issue by IndrajeetPatil** [jimhester/lintr#388]
The `{{` operator (as alternative to `!!` + `enquo`) was introduced in `rlang 0.4.0` (https://www.tidyverse.org/articles/2019/06/rlang-0-4-0/) and I've started using this new operator in my packages. 

But now `lintr` treats this as a lint and my PR builds are flooded with `lintr-bot` comments:
https://github.com/IndrajeetPatil/ggstatsplot/pull/255#issuecomment-507053456

![image](https://user-images.githubusercontent.com/11330453/60400133-e0e62400-9b3d-11e9-97b4-8f29d8062042.png)

Any way to make sure that this is not counted as a lint?

**Comment by russHyde** [comment]
By adding 
```
linters: with_defaults(open_curly_linter = NULL, closed_curly_linter = NULL)
```
to the `.lintr` file for your package you can turn off this pair of linters.

**Comment by russHyde** [comment]
Alternatively, _I think_ you could use
`linters: with_defaults(open_curly_linter = open_curly_linter(allow_single_line = TRUE), closed_curly_linter = closed_curly_linter(allow_single_line = TRUE))`

This would allow you to use `{{ some_columns }}` and `if (something) {this()} else {that()}`
but would still catch other curly-brace-related lints. [Proposed but never used]
