### ISSUE TITLE
Include right-assignment  in `assignment_linter`

### ISSUE THREAD

**Issue by russHyde** [jimhester/lintr#390]
`"the horror" -> run_away` isn't caught by the `assignment_linter` in `lintr` v1.0.3. 

Are we happy to have right-assignment included in the `assignment_linter` checks?

Should an update to `assignment_linter` also include `<<-`, `->>` and `assign()`?

**Comment by jimhester** [comment]
I like right assignment, so no I don't want to add it to the assignment linter.

Similarly `<<-` and `assign()` have their uses and should not be linted.
