### ISSUE TITLE
Why sapply and mapply are undesirable ?

### ISSUE THREAD

**Issue by Fablepongiste** [jimhester/lintr#417]
```
Function "sapply" is undesirable. As an alternative, use vapply() or lapply().
Function "mapply" is undesirable. As an alternative, use Map().
```

Do not really understand theses, they are different and have their use in some cases. Why would their usage be undesirable ?

**Comment by russHyde** [comment]
There's a paragraph at the end of section 9.2.1 of "Advanced R" where Hadley Wickham explains some issues with `sapply` (https://adv-r.hadley.nz/functionals.html#map-atomic).

Imagine you are separately passing two different sets of data through a function: when applied to the first set, you get a list, whereas when applied to the second set you get a matrix. This return-type uncertainty is at the root of the problem with `sapply`. `vapply` is more strict with respect to return types.

Ultimately, the choice is subjective, so this doesn't seem to be an "issue". So I'll close this thread soon.
