### ISSUE TITLE
sequence lintr proposes seq_len instead of seq_along for 1:length(...)

### ISSUE THREAD

**Issue by aryoda** [jimhester/lintr#418]
For code like

    1:length(aVectorOrAList)

I am getting lintr results saying

> Avoid 1:length(...) expressions, use seq_len

but I think the message should be

> Avoid 1:length(...) expressions, use seq_along

**Comment by russHyde** [comment]
In this instance both

- `seq_len(length(aVectorOrAList))` 

and

- `seq_along(aVectorOrAList)`

should work

**Comment by aryoda** [comment]
I think I can always use `seq_len` instead of `seq_along` but it is more code then (to call the `length` function) so what I am trying to say is to recommend the shortest possible solution as the lint proposal.

**Comment by russHyde** [comment]
That's true when working with a vector. But the linter also applies to `1:nrow(df)`, and in that setting `seq_len(nrow(df))` works but `seq_along(df)` doesn't (the latter makes a sequence of column indices).
I'm going to close this issue.

**Comment by aryoda** [comment]
I am somehow confused now. The linter message is explicitly saying

> Avoid 1:length(...) expressions

not

> Avoid 1:nrow(...) expressions

but I do not know the internal linter logic that is used to construct this message of course...

**Comment by russHyde** [comment]
That is true. But had your code said `1:nrow(...)` the same linter would have output `Avoid 1:nrow(...) expressions` and recommended that you use `seq_len(...)`. That is, although several different statements enrage the `seq_linter`, in each case that linter gives the same recommended fix: to use `seq_len(...)`, a fix that is valid in each case (the cases being `1:nrow(...)`, `1:length(...)`, `1:ncol(...)` etc etc; see the source code for `seq_linter` if you want to see how it's implemented)

**Comment by aryoda** [comment]
I am with you after looking into the source code, it works on a more generic base.
Thanks for taking the time!
