### ISSUE TITLE
Expand details of how to define a `.lintr` config

### ISSUE THREAD

**Issue by russHyde** [jimhester/lintr#419]
In thread https://github.com/jimhester/lintr/issues/374 there was some confusion as to how to set up a basic `.lintr` config file, eg, for use in a new project.

Was wondering whether the website section https://github.com/jimhester/lintr#project-configuration could be expanded to give more clarity on how to use `with_defaults(....)` in a `.lintr` file.

**Comment by russHyde** [comment]
Ref:
https://github.com/jimhester/lintr/issues/374
https://github.com/jimhester/lintr/issues/273

**Comment by russHyde** [comment]
I've added some preliminary info (based on the stuff in the README and the manpages) here: https://gist.github.com/russHyde/798220115fe84a812486258012d83d12

**Comment by maelle** [comment]
In a pkgdown website "how to tweak the configuration" could be a whole article. :-)

**Comment by MichaelChirico** [comment]
Can this be closed by #660?

**Comment by russHyde** [comment]
Yes. Closing
