### ISSUE TITLE
Issue with "visible global function" and ":::"

### ISSUE THREAD

**Issue by cannin** [jimhester/lintr#423]
For this code (NOTE: lines from the function were removed to produce a reproducible example): 

    #' Run Cross validation for data through the chosen algorithm.
    #'
    #' @param data input expression data.
    #' 
    #' @return result of validation score
    #'
    #' @importFrom glasso glasso
    #' @importFrom GeneNet ggm.simulate.pcor
    #' 
    #' @export
    runCrossValidation <- function(data, pc) {
      g_result <- glasso(pc, 1)
      p_off_d <- sum(g_result$wi != 0 & col(pc) < row(pc))
      random_pcor <- ggm.simulate.pcor(ncol(data), etaA = 1)
      stats:::var(c(1, 2, 3))

      return(1)
    }

and using this .lintr 

    linters: with_defaults(
      closed_curly_linter=NULL,
      commented_code_linter=NULL,
      extraction_operator_linter=NULL,
      function_left_parentheses_linter=NULL,
      implicit_integer_linter=NULL,
      infix_spaces_linter=NULL,
      line_length_linter(120),
      object_length_linter=NULL,
      seq_linter=NULL,
      single_quotes_linter=NULL,
      spaces_left_parentheses_linter=NULL,
      trailing_blank_lines_linter=NULL,
      trailing_whitespace_linter=NULL,
      undesirable_function_linter=NULL,
      object_name_linter("snake_case"),
      cyclocomp_linter=NULL, 
      commas_linter=NULL,
      undesirable_operator_linter,
      unneeded_concatenation_linter, 
      T_and_F_symbol_linter)

I get this lint output: 

    > lintr::lint("~/Downloads/tmp.R")
    ~/Downloads/tmp.R:2:15: warning: no visible global function definition for ‘glasso’
      g_result <- glasso(pc, 1)
                  ^~~~~~
    ~/Downloads/tmp.R:3:3: warning: local variable ‘p_off_d’ assigned but may not be used
      p_off_d <- sum(g_result$wi != 0 & col(pc) < row(pc))
      ^~~~~~~
    ~/Downloads/tmp.R:4:3: warning: local variable ‘random_pcor’ assigned but may not be used
      random_pcor <- ggm.simulate.pcor(ncol(data), etaA = 1)
      ^~~~~~~~~~~
    ~/Downloads/tmp.R:4:18: warning: no visible global function definition for ‘ggm.simulate.pcor’
      random_pcor <- ggm.simulate.pcor(ncol(data), etaA = 1)
                     ^~~~~~~~~~~~~~~~~
    ~/Downloads/tmp.R:11:1: style: Variable and function name style should be snake_case.
    runCrossValidation <- function(data, pc) {
    ^~~~~~~~~~~~~~~~~~

The following seem like bugs: 

1. "no visible global function definition for ‘glasso’" seems like a bug because there is an @importFrom statement. This might be connected to #67. What are my options other than to disable that linter completely?
2. The ":::" for stats:::var() is not picked up with the undesirable_operator_linter .lintr entry. 

This was done using lintr_2.0.0.9000 on R 3.6.1.

**Comment by russHyde** [comment]
Re your second point, could you try `with_defaults(..., undesirable_operator_linter = undesirable_operator_linter(), ...)`

**Comment by russHyde** [comment]
Re your first point, could you check that there is an importFrom(...) statement in your NAMESPACE file first, and, if not, run 'devtools::document()' before running lintr;

**Comment by cannin** [comment]
> Re your second point, could you try `with_defaults(..., undesirable_operator_linter = undesirable_operator_linter(), ...)`

undesirable_operator_linter=undesirable_operator_linter() works, but then if I do "T_and_F_symbol_linter=T_and_F_symbol_linter()" (for consistency), I get: 

    > lintr::lint("tmp.R")
    Error in ids_with_token(source_file, "SYMBOL") :
      argument "source_file" is missing, with no default

or unneeded_concatenation_linter=unneeded_concatenation_linter(), I get 

    > lintr::lint("tmp.R")
    Error in filter_out_token_type(source_file[["parsed_content"]], "expr") :
      argument "source_file" is missing, with no default

Did I miss something in the documentation?

**Comment by cannin** [comment]
> Re your first point, could you check that there is an importFrom(...) statement in your NAMESPACE file first, and, if not, run 'devtools::document()' before running lintr;

I had already added importFrom statements into my NAMESPACE file such as: 

    importFrom(GeneNet,ggm.simulate.pcor)
    importFrom(ggplot2,ggplot)
    importFrom(glasso,glasso)

among others. Some of these lintr initially flagged, but glasso is being stubborn even with the importFrom statements in NAMESPACE. Worse, but harder to show as a reproducible example because I cannot make the code public, the line numbers that lintr reports do not have the glasso function. They might have at some point (I've been editing a lot). It is as if there is some set of stored results for lintr that are not getting cleared out.

**Comment by russHyde** [comment]
I'm not sure which bit of the documentation you read, but I don't think it's flagged up with any particular clarity. There is a set of default linters, and a bunch of other linters. If you want to include one of the non-default linters in your active linters (or modify teh default linters), for the most part you can do it using 

~~~
linters = with_defaults(some_name = name_of_linter)
~~~

This format doesn't work for:
closed_curly_linter(allow_single_line = FALSE)
todo_comment_linter(todo = c("todo", "fixme"))
cyclocomp_linter(complexity_limit = 25)
object_name_linter(styles = "snake_case")
object_length_linter(length = 30L)
line_length_linter(length)
open_curly_linter(allow_single_line = FALSE)
absolute_path_linter(lax = TRUE)
nonportable_path_linter(lax = TRUE)
semicolon_terminator_linter(semicolon = c("compound", "trailing"))
undesirable_function_linter(fun = default_undesirable_functions)
undesirable_operator_linter(op = default_undesirable_operators)

These are all the linters listed in the linters man page `? linters` that don't have `source_file` as their argument. These functions are linter builders - you need to evaluate them and they will return a linting function. That is, to generate a function that will lint the name-style of any newly-defined object, you use `object_name_linter(styles = my_required_styles)`. So `object_name_linter` isn't a linting function, but the function returned by `object_name_linter()` is a linting function.

So, `T_and_F_symbol_linter` is a linting function, but `undesirable_operator_linter` is a linter builder and you have to evaluate the latter to create a linter.

Apologies if thats not  very clear

**Comment by russHyde** [comment]
The simplest work-around for your glasso issue is to use `glasso::glasso(pc, 1)`

**Comment by cannin** [comment]
> The simplest work-around for your glasso issue is to use `glasso::glasso(pc, 1)`

Thanks for the fast response. Let's go with that; putting glasso::glasso() works. That resolves both mentioned issues. 

Something lingering is that I notice that lintr sometimes does reports incorrect line numbers. It should be ignored for now because I do not have a reproducible example, but maybe someone will come across this that does and know they are not the only ones.

**Comment by russHyde** [comment]
Yeah I've noticed the line number thing in vim before now, but I'm not sure how to debug it.
