### ISSUE TITLE
na.rm argument throws a snake_case note

### ISSUE THREAD

**Issue by msberends** [jimhester/lintr#425]
As discussed in #422: 

Creating a function with argument `na.rm` should not throw a note, as this argument is extremely common in base R and consequently (presumably) adopted by many developers.

```r
tmp <- tempfile()
writeLines("test <- function(a, na.rm = FALSE) a", tmp)
lintr::lint(tmp)
#> Line 1 Variable and function name style should be snake_case.
```

**Comment by MichaelChirico** [comment]
Understand it feels a bit odd given the ubiquity of `na.rm`, but in fact that argument name is not `snake_case` conformant.

`object_name_linter` supports the following `styles`:

```
symbols, CamelCase, camelCase, snake_case, SNAKE_CASE, dotted.case, lowercase, UPPERCASE
```

Your other alternative is to `# nolint` this special case if you are really unwilling to have an `na_rm` argument.
