### ISSUE TITLE
"Curly-braces... own line" exception to the rule: function stubs

### ISSUE THREAD

**Issue by aaronrudkin** [jimhester/lintr#428]
The curly brace messages make sense in virtually every case. Today I ran into a complaint from the linter about function stubs. For instance:

```
x <- function() { }
```

This is clearly aesthetically preferable to
```
x <- function() {
}
```

Why would you use a function stub? 

1. Mocking out an API. 
2. Writing a unit test for any function that takes a function as an argument -- in my particular case I have an error handler which inspects the formals of a function but doesn't care about the function itself, so function stubs are ideal. I use it because I have a function that allows the user to override some default calculations by providing an external function with identical formals.

So given this, I choose to use single line inline braces as shown in the first example. The other place the one-line inline braces might come up in R is single statement conditionals -- especially flow control like break/next in the `if(cond) { next }` format. However, you can solve that by ditching braces entirely -- the following is valid:

```
if(cond) next
```

Unfortunately, there is no equivalent for function stubs. The following is not legal:
```
x <- function()
```

I know you guys don't generally like error reports that boil down to "I like your style guide, except I don't like this part, so make an exception for me". So apologies in advance if that's what this comes off as. But I think this is an interesting corner case that might be worth adjusting the grammar of the rule. Totally reasonable if you disagree.

Any thoughts?

**Comment by russHyde** [comment]
@aaronrudkin The `closed_curly_linter` seems to already support this. Sorry I didn't notice sooner.
In your .lintr config, you can use 

```
linters: with_defaults(
  closed_curly_linter = closed_curly_linter(allow_single_line = TRUE)
)
```

and that should no longer flag your `f <- function() { }` one-liners
