### ISSUE TITLE
Check for space after "<-" assignment eg "x<-5" is BAD

### ISSUE THREAD

**Issue by klin333** [jimhester/lintr#434]
R tidyverse style guide recommends: 
x <- 5

This implicitly recommends a space after the "<-" operator, because without this space, the expression is ambiguous and very prone to bugs, eg does "x<-5" mean "x <- 5" (assignment) or "x < -5" (inequality test)

Recommends a new linter to check for the existence of 1 space character after an "<-" operator.

**Comment by russHyde** [comment]
The issue that you raise is already handled by `infix_spaces_linter` (which "check[s] that all infix operators have spaces around them.").

Could you try running lintr on your code with that linter enabled and check that it isn't missing any "x<-5", "x <-5" or "x<- 5" examples.

If it is, could you post a more detailed issue, containing details of the version of R/lintr you are using (as in, eg, the output from sessionInfo()) and some example code that isn't caught by `infix_spaces_linter`)

**Comment by klin333** [comment]
I see, my bad, thanks! I had the infix linter turned off. 

I would still think a separate linter for this special case of an infix operator "<-" would be useful, or maybe change infix_spaces_linter to be customisable (eg like line_length_linter) so users can select which infix operators to check for. The reason being:

1. Many people may want the infix linter turned off, as many people may want to group/space mathematical expressions in a way that is intuitive to them, eg "3*a1*a2 + 4*b2*b2"
2. Almost everyone should have the "<-" spacing linter switched on, because it is such a special case of an operator. It is such a weird characteristic of R (<- instead of =) that really should have safeguards around. Also, it is one of the few R infix operators where a lack of space can change the operation. 

Thanks for ideas and thoughts on this.

**Comment by MichaelChirico** [comment]
Closing since I that's out of scope for `lintr`, which follows the tidyverse style guide that doesn't allow this mixing:

https://style.tidyverse.org/syntax.html#spacing

Relevant suggestion about relaxing this restraint when mixing operator precedences: https://github.com/tidyverse/style/issues/160
