### ISSUE TITLE
lintr::lint_package should lint vignettes by default

### ISSUE THREAD

**Issue by AshesITR** [jimhester/lintr#447]
Since linting is possible for vignettes, it should be the default for `lintr::lint_package()` to also lint package vignettes.

This line just needs `"vignettes"` as an additional directory and `"\\.[Rr](md|)$"` as a pattern for that to work:

https://github.com/jimhester/lintr/blob/dbc76246c244e89f04be3031ff6db1dbe26960ac/R/lint.R#L238

**Comment by russHyde** [comment]
This seems quite reasonable, @AshesITR would you be interested in implementing this?

**Comment by AshesITR** [comment]
Sure thing 👍
