### ISSUE TITLE
Errors out of the list given below in the link

### ISSUE THREAD

**Issue by rahulrachh** [jimhester/lintr#469]
I am using lintr on certain files and i am getting errors that are not in the list of Available linters given here at: [link](https://cran.r-project.org/web/packages/lintr/readme/README.html#available-linters)
Also, how to know whether these are messages belong to error, warning or style/info category ?

In the output i get the text but i am not able to get the name of the linter that gives me these output. Some of the messages and their type are:

`local   variable "variable-name" assigned but may not be used - warning`
`no   visible global function definition for 'function-name' - warning`
`unexpected   numeric constant - error `
`no   visible binding for global variable 'sel' - warning `
`unexpected   end of input - error`
`Only   use double-quotes - style/info`

I am using:
R - 3.6.3 - 32 - bit
lintr - 2.0.1

**Comment by russHyde** [comment]
How are you running lintr? In rstudio using a plugin, from the R prompt, or is it autorunning in an editor like vim or atom. If you are using the R prompt, could you post the commands that you type, please.

The first of your lines is from `object_usage_linter`, and you can see the category (warning) of the lint at the end of the line

**Comment by rahulrachh** [comment]
I am running it in cmd and Rstudio both. In Rstudio, I run 
`library(linte)` and then `lint('newfile.R')` in R prompt in Rstudio 
and 
in cmd I run 
`Rscript -e "lintr::lint('newfile.R')"`. 

How did you got that the first one is called `object_usage_linter` ? I am asking about the type of the messages that are in this [link](https://cran.r-project.org/web/packages/lintr/readme/README.html#available-linters). I got the above mentioned errors and their type by getting the output of lintr in xml format by using `checkstyle_output()` function.

**Comment by russHyde** [comment]
Could you try using `Rscript -e "lints <- lintr::lint('newfile.R'); cat(as.data.frame(lints))"`

**Comment by rahulrachh** [comment]
Yeah that worked. `cat` is not working but i am getting the output as dataframe in R console. Thanks. Also, look at the other issue I face at [link](https://github.com/jimhester/lintr/issues/470)
