### ISSUE TITLE
Is there a way to get custom output of lintr in R in the cmd ?

### ISSUE THREAD

**Issue by rahulrachh** [jimhester/lintr#470]
I know there exist a function that will give me the output in XML. I was wondering is it possible to change the output I get in cmd. 
For e.g CMD output gives me:
`path/of/file:row:col:error-type:error-text`. 
Can this be modified to:
`LINE:row:error-type:error-text` ? 
Thats is what I am asking.

I am using:
R - 3.6.3 - 32-bit
lintr - 2.0.1

**Comment by russHyde** [comment]
Please show 
- a (short) example of a file you are analysing,
- an actual example of the results that you obtaining from the command line (for the example file),
- how those results differ from your expectations,
- and how you are calling lintr in this instance.

Is your LINE the same as lintr's row? If it is, you should look at `cut` in bash.

As it stands this is neither a bug nor a feature request (for a given lint, most users would want to know the file where it originated)

**Comment by rahulrachh** [comment]
Okay thanks that was helpful. I got it.
