### ISSUE TITLE
Github Action?

### ISSUE THREAD

**Issue by yannickwurm** [jimhester/lintr#486]
Could someone create a github action to run this automatically on private repos that contain .R or .Rmd files?  (without requiring a Travis subscription)

**Comment by russHyde** [comment]
I believe Jim added this in this PR: https://github.com/jimhester/lintr/commit/084674c00a3110132b8ec541d2d2a5617a120b1b .

**Comment by yannickwurm** [comment]
ooh that is awesome. It doesn't show up when I browse the github actions page tho -  Do you know when that might happen /how to get it into there?

**Comment by russHyde** [comment]
GHA details have added to README. https://github.com/jimhester/lintr#github-actions

Closing.

**Comment by yannickwurm** [comment]
Super - thank you!
