### ISSUE TITLE
Excluding renv directory using lintr::lint_dir()

### ISSUE THREAD

**Issue by prncevince** [jimhester/lintr#492]
Using version 2.0.1 of lintr, I believe that the software cannot ignore files and directories within an `renv` directory. Because `renv` uses symbolic links, lintr may have issues with ignoring symbolic links. 

Command used in root directory of Rproject:

`lintr::lint_dir(exclusions = list.files("renv", full.names = T, recursive = T, all.files = T))`

Error generated:

```
Error in read_xml.raw(charToRaw(enc2utf8(x)), "UTF-8", ..., as_html = as_html,  :
  PCDATA invalid Char value 12 [9]
Calls: <Anonymous> ... FUN -> <Anonymous> -> read_xml.character -> read_xml.raw
Execution halted
```

After continued digging, it appears that lintr is getting caught up on random `.R` files within packages of my renv library at `renv/library/R-3.6/x86_64-apple-darwin15.6.0/` .

**Comment by russHyde** [comment]
You can now exclude by directory name. Could you confirm whether `lintr::lint_dir(exclusions = "renv")` solves your problem with the dev version of lintr, please.

**Comment by prncevince** [comment]
This worked for me! Maybe add `renv` & `packrat` by default? This is what the folks working on the [styler](https://github.com/r-lib/styler) package are trying to do.
- https://github.com/r-lib/styler/issues/562
