### ISSUE TITLE
Newline at end of file linter

### ISSUE THREAD

**Issue by jimhester** [jimhester/lintr#50]
while `readLines` does throw a warning in this case we should also generate a lint (and probably catch the warning).

This error is basically impossible to generate using vim and emacs, but very easy to do with RStudio.

**Comment by Arcanemagus** [comment]
This is also pretty easy to trigger within Atom since the new integration in there lints the contents on the fly.

**Comment by jimhester** [comment]
@Arcanemagus I just updated the atom linter code to append a newline to the file from the buffer, which fixes this issue https://github.com/AtomLinter/linter-lintr/commit/7ff6d0cad94afe3569944512609117a6889afaec.

**Comment by MichaelChirico** [comment]
OG version of #675 / #719; closing as superseded by those
