### ISSUE TITLE
Add to the GitHub Super Linter

### ISSUE THREAD

**Issue by nathaneastwood** [jimhester/lintr#501]
Would be nice to get lintr added to the [GitHub Super Linter](https://github.blog/2020-06-18-introducing-github-super-linter-one-linter-to-rule-them-all/)

EDIT: [Link to the repo](https://github.com/github/super-linter)

**Comment by jimhester** [comment]
I am pretty pessimistic that GitHub would include lintr in that, as it would require them to include an R runtime in the docker container. If you think it would be useful and are interested I would suggest opening an issue at the repo you linked to.

**Comment by nathaneastwood** [comment]
Thanks Jim. I raised it [here](https://github.com/github/super-linter/issues/262). Let's see what they say.

**Comment by assignUser** [comment]
I tried to implement it, would be grateful for feedback as this is my first docker project: https://github.com/github/super-linter/pull/569

**Comment by assignUser** [comment]
Done, my pr was merged 👍

**Comment by AshesITR** [comment]
Thanks for taking the time!
