### ISSUE TITLE
Send lintr output to file

### ISSUE THREAD

**Issue by belokoch** [jimhester/lintr#509]
I'd like to save the lintr output from the Markers pane to a file. I can't find that feature. I'm also not able to sync() it to a log file. This feature would be helpful for documenting package development.
Thanks!

**Comment by AshesITR** [comment]
Have you looked at the result of `format(lintr::lint_package())`?
The return value of `lint_package()` is a list of lints, `lintr:::print.lints` is what makes use of the source marker pane.

**Comment by belokoch** [comment]
I wasn't thinking "return value" and that was exactly what I needed. Thanks for your response and patience. 

I'm going to output the data frame as a linting log. 

I found  "lintr::as.data.frame.lints()" mentioned in a google search, but couldn't find it in the packages window in RStudio under lintr. It is a nice function. 

At first I was going to go with this:
lntr_out<-as.data.frame( lintr::lint_package(), stringsAsFactors = FALSE )

but I think I will go with this instead:
lntr_out<-lintr:::as.data.frame.lints(lintr::lint_package()) 

Thanks again!
