### ISSUE TITLE
Clearly document which linters are `default_linters`

### ISSUE THREAD

**Issue by stufield** [jimhester/lintr#510]
It is currently somewhat difficult to go through the `?lintr::linters` and easily see which linters correspond to `default_linters`. Additionally, `?lintr::default_linters` does not actually list the names of the default linters. 

One could `names(lintr::default_linters)` and then compare those to the documentation, but this seems unnecessarily tedious. 

Suggest clearly splitting out the `default_linters` from other linters` in the documentation (with a Section?). And also listing the default linters in `?lintr::default_linters`? Perhaps here a link to `?linters` will suffice if they are split out clearly.

I can submit a PR if people agree this is useful (and no one really wants to work on docs)

**Comment by russHyde** [comment]
This seems very useful. The documentation would benefit from a bit of work.

**Comment by AshesITR** [comment]
At this point the list of linters is so long, it might be beneficial to order them into separate topics.
Is there a simple way to generate multiple docs for the same function?

Maybe at ?my_linter, ?default_linters and ?linters as well as maybe some ?my_linter_topic pages, all interlinked nicely?

Ideally ?my_linter would only show the help of that specific linter (so one can quickly find the available configuration options / argument documentation) and the others would be lists of linters akin to the current ?linters

**Comment by russHyde** [comment]
By changing the roxygen for `default_linters` we could generate the following on calling `?default_linters`

```
default_linters             package:lintr              R Documentation

Default linters

Description:

     List of default linters for ‘lint’. Use ‘with_defaults’ to
     customize it.

     The set of default linters is as follows

     names(default_linters)

     ##  [1] "assignment_linter"                "closed_curly_linter"
     ##  [3] "commas_linter"                    "commented_code_linter"
     ##  [5] "cyclocomp_linter"                 "equals_na_linter"
     ##  [7] "function_left_parentheses_linter" "infix_spaces_linter"
     ##  [9] "line_length_linter"               "no_tab_linter"
     ## [11] "object_length_linter"             "object_name_linter"
     ## [13] "object_usage_linter"              "open_curly_linter"
     ## [15] "paren_brace_linter"               "pipe_continuation_linter"
     ## [17] "seq_linter"                       "single_quotes_linter"
     ## [19] "spaces_inside_linter"             "spaces_left_parentheses_linter"
     ## [21] "trailing_blank_lines_linter"      "trailing_whitespace_linter"

Usage:

     default_linters
```

---
Changes:
```
#### in zzz.R 

#' Default linters                                                                                                                             
#'                                                                                                                                             
#' @description List of default linters for \code{\link{lint}}. Use                                                                            
#' \code{\link{with_defaults}} to customize it.                                                                                                
#'                                                                                                                                             
#' The set of default linters is as follows                                                                                                    
#'                                                                                                                                             
#' ```{r}                                                                                                                                      
#' names(default_linters)                                                                                                                      
#' ```                                                                                                                                         
#'                                                                                                                                             
#' @export
```


```
### In DESCRIPTION
...

Roxygen: list(markdown = TRUE)

...
```

**Comment by russHyde** [comment]
What that misses is the arguments for `line_length_linter` etc

**Comment by AshesITR** [comment]
We don't strictly need to enable markdown, cf.

https://github.com/jimhester/lintr/blob/3a7ec5ce13acdb7ef7bf9d47a05777f0838744a0/R/object_name_linters.R#L3

I think it would be nice to stick to one way of documenting things.
Since markdown formatting is nicer to read and easier to use IMO, we could start a migration effort if desired?
