### ISSUE TITLE
How to disable assignment_linter in VS-code?

### ISSUE THREAD

**Issue by albert-ying** [jimhester/lintr#516]
Hi, there is no example of how to config linter in vs-code. I want to globally disable the assignment_linter, how can I do that? Thank you!

**Comment by renkun-ken** [comment]
As described by https://github.com/jimhester/lintr#project-configuration, you could put `~/.lintr` with the following content:

```
linters: with_defaults(assignment_linter = NULL)
```

Then `assignment_linter` will be globally disabled for you unless the project config says otherwise.
