### ISSUE TITLE
Allow exclusion of directories

### ISSUE THREAD

**Issue by AshesITR** [jimhester/lintr#518]
When using `renv` in a project, `lintr::lint_dir()` will try to lint all packages installed in the library (`renv/library/...`)
Currently, one can only exclude single files, so there is no practical way to lint projects using `renv`.

A remedy would be support for excluding entire directories from linting.

**Comment by jucor** [comment]
Most useful for `renv` indeed. Sadly this issue is what's preventing from using `lintr` as a pre-commit hook when `renv` is in use. Instead I manually run `devtools::lint()` in Rstudio. Not as nice :)
