### ISSUE TITLE
Start from .RProfile

### ISSUE THREAD

**Issue by razz-matazz** [jimhester/lintr#519]
Hello,

I am trying to start lintr::lint_dir() from a .rprofile file of a project to check all .R files of that project at opening the project in RStudio.

To be sure RStudio is up running when I call that function I put it in
```setHook("rstudio.sessionInit", function(newSession) { ... }```

but I neither get a error message nor does the pane "Marker" open (though the dots change from "." to ".." to "...").

Running lintr::lint_dir() from the open project works. Other lines of code in the hook also work.

Is there a way to make lintr work at project startup?

**Comment by AshesITR** [comment]
It might be called too early during session initialisation.
Can you try this?

```r
.First <- function(){later::later({
  lintr::lint_dir(".")
})}
```

**Comment by razz-matazz** [comment]
Hello,
> ```r
> .First <- function(){later::later(~{
>   print(lintr::lint_dir("."))
> })}
> ```

This works. But without print it doesn't. Seems RStudio is not ready at that moment :/
