### ISSUE TITLE
package names not be linted

### ISSUE THREAD

**Issue by jimhester** [jimhester/lintr#53]
if a name is in a library call it should be camelCase.

A workaround to this is just to quote the library name.

**Comment by jimhester** [comment]
This is such a specific case I am not sure it is worth doing.  On the other hand it is so common in Scripts it probably should be done. :expressionless:

**Comment by pwildenhain** [comment]
Hello Jim, 

when I run this code, I get a lint marker because of the `REDcapR` library.

```
library(httr)
library(REDCapR)
library(odbc)
library(dplyr)
library(readr)
``` 
The marker says `Variable and function names should be all lowercase`. Would this issue also address my example?

**Comment by jimhester** [comment]
Yeah, a workaround is to quote the package names.

**Comment by pwildenhain** [comment]
Got it, thanks!

**Comment by jimhester** [comment]
Now I think we should just not check for names within `library()` calls.

**Comment by jimhester** [comment]
This seems to be fixed in the current devel
