### ISSUE TITLE
Choosing specific linters in SublimeText3

### ISSUE THREAD

**Issue by MalteThodberg** [jimhester/lintr#54]
I just got SublimeLinter+lintr and R-Box working in ST3

I'm mainly interested in only a few selected linters - how do I modify the 'linters' settings in the following lines in the SublimeLinter user-settings file to use only, say,  Syntax Error, object_usage_linter and absolute_paths_linter?

{
    "user": {
        "linters": {
            "lintr": {
                "@disable": false,
                "args": [],
                "cache": "TRUE",
                "excludes": [],
                "linters": "with_defaults(line_length_linter(120))"
            }
        }
    }
}

Thanks for making a great package!

**Comment by jimhester** [comment]
The linters line is really just a list of linters you would like to use.  The with_defaults line is simply to make it easy to change only a few linters from the defaults.  So if you want to only use the two linters you mentioned just make a list with only those two enabled.

```r
"linters": "list(object_usage_linter, absolute_paths_linter)"
```

The syntax error lints come from the initial code parsing so they don't have a linter (and can't be turned off).
