### ISSUE TITLE
readLines warning for incomplete final line

### ISSUE THREAD

**Issue by MichaelChirico** [jimhester/lintr#542]
Found in many packages, e.g. `nsprcomp`:

```
tmp = tempfile()
download.file('https://raw.githubusercontent.com/cran/nsprcomp/master/R/asdev.R', tmp)
lintr::lint(tmp)
# incomplete final line found on '/tmp/RtmptJEp8r/file3fb841ddb96d'
```

It's because `get_source_expressions` uses `readLines` without `warn=FALSE`. This is easy enough to fix; filing the issue first, since this might be considered a lint as well.

**Comment by AshesITR** [comment]
I like the idea of incomplete final lines causing a lint.
This error bit me more than once in `Renviron.site` files...

**Comment by MichaelChirico** [comment]
what do you think of a new attribute on the source_file object like
$has_final_newline? it gets populated during parsing & then the linter
simply returns this

**Comment by AshesITR** [comment]
Would any other linter need it?
I'm thinking it might be simpler to just read the source file in the linter to check for presence of the final line.

**Comment by MichaelChirico** [comment]
The problem is `readLines` flattens the difference between terminal-newline and no-terminal-newline files:

```
writeLines("lm(y ~ x)", tmp <- tempfile())
writeBin(
  head(readBin(tmp, raw(), file.size(tmp)), -1L),
  tmp2 <- tempfile()
)
identical(readLines(tmp), readLines(tmp2, warn=FALSE))
# [1] TRUE
```

So we'd have to `readLines` each whole file again in the linter, seems pretty inefficient to me. The alternative to force-append `'\n'` to `lines` when a newline is present also seems less than ideal.

I would lean towards allowing the split logic in this case, it's an exception (very few linters are file-level), and I think the linter code would be very short & pretty easy to figure out what's going on (especially with a helpful comment :smiley:)

**Comment by AshesITR** [comment]
Good point about need to re-read all files.
We should catch the warning from `readLines` and store it to guarantee that we use the same definition for "incomplete final line" as R uses.
