### ISSUE TITLE
Malformed file! message for imbalanced chunk gates is not helpful

### ISSUE THREAD

**Issue by MichaelChirico** [jimhester/lintr#571]
```
writeLines("```{r chunk}
lm(x ~ y)
", tmp <- tempfile(fileext = '.Rmd'))
lintr::lint(tmp)
# Error: Malformed file!
```

This error message should be improved

**Comment by AshesITR** [comment]
I agree the current message isn't very helpful.
What do you think about "Missing chunk end for chunk starting at line XXX" for an error message?

**Comment by MichaelChirico** [comment]
It is already thrown as an error lint, sorry I should have made that clearer. But the message doesn't help diagnose.

Are you sure we'll always be able to disambiguate well enough to know which chunk is missing the end? Especially in scripts that have mixed R chunks & plain code chunks, something like (using `'''` as backticks here not to mess around with escaping in GH markdown):

```
'''{r chunk}
lm(x ~ y)


# some text

'''
bash some_script.sh
'''
```

I think by eye it's clear the first chunk is incomplete, but a simple parser would likely say the second one is.

I think it's less effort/safer to just say "incomplete chunk -- all chunks must begin and end with `'''`", at least then it gives the nature of the error & user can take it from there.

**Comment by AshesITR** [comment]
I was thinking of adding the line info to the lint.
While yes, such errors might have inaccurate line infos, I still think if they hit 90% of the time, it's fine to be inaccurate.

It would always find the problem i.e. if

````
```{r chunk-1}
code <- 42

# A heading
Some text

```{r chunk-2}
some_more_code <- 42
```
````
