### ISSUE TITLE
incorrect assumption that any string starting with forward slash is a path

### ISSUE THREAD

**Issue by jackwasey** [jimhester/lintr#58]
`gsub(pattern = "/\\*.*?\\*/", replacement = "", x = text)`
gives lint warning about absolute paths.

**Comment by jimhester** [comment]
This unfortunately can't really be helped :frowning:. Theoretically the above could be a absolute path with a very weird filename.  

Solutions would be to turn off that linter, exclude that line from linting (`# nolint` is the default) or just deal with the extra lint.

To fix this in code you could do something complicated like register all the functions in base packages which take filenames and only check those, but it seems like quite a bit of effort to keep that updated and there would be false negatives from user created functions.  I think this is just an issue we are going to have to live with.
