### ISSUE TITLE
Make R/ conform to `paren_brace_linter`

### ISSUE THREAD

**Issue by AshesITR** [jimhester/lintr#603]
Part of #584 

- [x] enable `paren_brace_linter` in `.lintr`
- [x] run `lintr::lint_package()` to find all lints
- [x] fix all lints

**Comment by MichaelChirico** [comment]
This one requires #467

**Comment by russHyde** [comment]
Since #620 has been merged, I'll work on this today.

**Comment by russHyde** [comment]
After enabling `paren_brace_linter`, no lints were observed when running `lint_package`
