### ISSUE TITLE
Feature: allow turning off specific linters per-line

### ISSUE THREAD

**Issue by AshesITR** [jimhester/lintr#605]
It might be useful to disable only a specific linter on a per-line basis, e.g.

```r
`%||%` = function(x, y) {
  if (is.null(x)) y else x
}
```

produces two default lints: `object_name_linter` and `assignment_linter`.
One may actively decide that `%||%` is an acceptable name here and not want to generally disable `object_name_linter`.

Currently, this can only be achieved by # nolint'ing the entire line
```r
`%||%` = function(x, y) { # nolint
  if (is.null(x)) y else x
}
```
but unfortunately this also kills the `assignment_linter`

It would be very useful to have a way to only exclude some linters on a line (or in a block).
A syntax might be a space-separated list of linters to be disabled, e.g.

```r
`%||%` = function(x, y) { # nolint object_name_linter
  if (is.null(x)) y else x
}
```

I realize this would require work in the way exclusions are specified. Especially the line-based specification in `.lintr` files or the `exclusions` argument requires thought.

One solution would be one more level of (optional) nesting

```r
exclude: list(
    "my_file.R" = list(
      1,
      "2" = "object_name_linter",
      "4" = c("line_length_linter", "commented_code_linter")
    )
  )
```

**Comment by AshesITR** [comment]
Another usecase would be to enforce the location of `library()` calls in some centralized location for larger analysis projects.
You could define `library_linter = undesirable_functions_linter(c("library" = "place all library() calls at the top of main.R"))`
and combine that with a section like

```r
# nolint start library_linter
# Place all necessary library() calls here
library(tidyverse)
# nolint end
```

**Comment by MichaelChirico** [comment]
I agree and this feature is key to preventing code from slowly getting
worse in some gated off sections -- if we limit the gating to a specific
linter, and either the code is changed or new liners are added in the
future, it can continue to be detected.

Have had this on my back burner to bring up, but haven't thought of a good
API for it.

# nolint(...)
# lintr: off(...)

where ... are linter names?

I'm not sure that extends easily to all custom nolint tags, however.

**Comment by AshesITR** [comment]
I think whatever the API becomes, it should be specified as some well-defined suffix of the (user-configured) `# nolint` and `# nolint start` tags.

Tending against parenthesis because that looks akward for block exclusions:

```r
# nolint start(library_linter, object_name_linter)
```

**Comment by MichaelChirico** [comment]
Also note that a blanket inclusion of things after the `# nolint` tag is likely not to work (or at least to be awkward), as it's not uncommon to write some notes there about why that line's nolinted (I know I do this for `covr` especially), e.g.

```
someReallyLongLineActuallyLongerThan120Chars # nolint this object is defined elsewhere, no choice but to use here
```

which is why I think we'll need some sort of glyph to signal "this is naming linters, not free text"

**Comment by AshesITR** [comment]
What about a colon and a dot?

`# nolint: library_linter, object_name_linter. This is free text and will not be interpreted`

`# nolint start: library_linter. This ...`
