### ISSUE TITLE
pattern in signature of lint_package

### ISSUE THREAD

**Issue by MichaelChirico** [jimhester/lintr#631]
`R CMD check` gives us a `NOTE`:

```
lint_package: no visible binding for global variable ‘pattern’
Undefined global functions or variables:
```

That's because of here:

https://github.com/jimhester/lintr/blob/5128b4095bde779e0c9c20f543847c56949ecb74/R/lint.R#L260

It looks copy-pasted from `lint_dir`, but `lint_package` doesn't have a `pattern` argument -- should it? Or should we remove that line from `normalize_exclusions`?

**Comment by AshesITR** [comment]
`pattern = NULL` should produce the intended behaviour in case of a direct call to `lintr::lint()` so I think it can be removed.

**Comment by russHyde** [comment]
Tagged with 3.0.0 since this will need fixing before cran submission.
