### ISSUE TITLE
GitHub comment fails on private repos

### ISSUE THREAD

**Issue by lukebaker** [jimhester/lintr#64]
Travis.com allows tests to be run on private GitHub repos. However, the comments fail because the comment_token doesn't have access to the private repo. Here's the error message:

<pre><code>Error in stop(httr::http_condition(response, "error", message = httr::content(response,  : 
  {
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
Calls: print -> print.lints -> github_comment
</code></pre>

For our purposes, it'd be nice to simply turn off GitHub commenting entirely. However, it might also be a good idea to have this fail a bit more gracefully and not halt the program. When this happens, we don't see any of the lint results in our Travis CI logs.

**Comment by jimhester** [comment]
Both fair points, thank you for opening the issue.

**Comment by jimhester** [comment]
@lukebaker could you set the environment variable `LINTR_COMMENT_BOT=false` in your build environment and see if that fixes your issue.  That should turn off the lintr-bot.

**Comment by naupaka** [comment]
Would there be a way to have the commenting work on private repos? Perhaps through a special token from a secondary CI-user account? I'm using this in a class where we are working in private repos, and so having the ability to have linting comments get added on e.g. PRs automatically would be awesome.

**Comment by naupaka** [comment]
For example, perhaps there could be a way to make this an optionally settable environment variable (like the option to turn off the bot) here: https://github.com/jimhester/lintr/blob/87658ec425ca5cb2c733444ab6beef45dbb31cfe/R/zzz.R#L198

The user could set it as an encrypted token with the appropriate permissions?

**Comment by jimhester** [comment]
Yeah possibly that could work. I personally do not have any private repos to test this on, so if you make and test the change and submit a PR I will definitely look at it.

**Comment by naupaka** [comment]
OK, sounds good, thanks for the response. I'll see what I can do with it this weekend and if I figure it out I'll submit a PR.

**Comment by nikolase90** [comment]
Any update on this issue?
