### ISSUE TITLE
Incomplete migration to GHA

### ISSUE THREAD

**Issue by AshesITR** [jimhester/lintr#643]
Hi @jimhester, the required build status `continuous-integration/travis-ci` is still active and currently prevents merges.
Could you please remove it from the project settings and add the GHA equivalents instead?

Many thanks!

**Comment by jimhester** [comment]
I have now disabled the project on travis-ci.org and deleted the webhook.

**Comment by AshesITR** [comment]
I'm afraid it's still present _somewhere_.
I just added a fresh commit to trigger CI on #638 and the list includes travis :/

**Comment by AshesITR** [comment]
Update: Even creating a brand-new PR from a brand-new commit on a brand-new branch doesn't help: #647 created. Feel free to (ab)use that PR to test if anything worked.

**Comment by MichaelChirico** [comment]
per comment here, I think Travis is still listed as a blocker for protected
branches, I think we need to wait for Him:

https://github.com/jimhester/lintr/pull/638#issuecomment-735988426

**Comment by jimhester** [comment]
Ok I found the setting for this, I now set it so that it needs green builds on the release builds
