### ISSUE TITLE
Emacs lintr.el reference on README is broken

### ISSUE THREAD

**Issue by aguereca** [jimhester/lintr#66]
Was this file dropped intentionally on a previous commit or there is another repo that host it?
Broken link is: https://github.com/jimhester/lintr/raw/master/inst/flycheck/lintr.el

**Comment by jimhester** [comment]
lintr support is now integrated directly into the flycheck installation, so there is no need to install a separate file.

I updated the README mentioning that, but did not delete the installation instructions, sorry for the confusion.

**Comment by aguereca** [comment]
Thanks for the pointer, will take a look into it.
