### ISSUE TITLE
Remove context() from tests

### ISSUE THREAD

**Issue by AshesITR** [jimhester/lintr#665]
See https://www.tidyverse.org/blog/2020/10/testthat-3-0-0/ -- it's already kind of vestigial, and will be deprecated from testthat 3.0.0

_Originally posted by @MichaelChirico in https://github.com/jimhester/lintr/pull/648#discussion_r533091065_

`context()` calls should be removed from all test files.

Some test files currently define multiple contexts.

* `test-exclusions.R` (3 contexts) should be split into separate files
* `test-cache.R` (tons of contexts) should go without contexts, maybe update `test_that()` descriptions.

The vignette `creating_linters.Rmd` recommends using `context()`. That should also be removed.

**Comment by AshesITR** [comment]
#660 splits `test-exclusions.R`.

**Comment by AshesITR** [comment]
The rest is handled in #696

**Comment by MichaelChirico** [comment]
Closes in #696
