### ISSUE TITLE
Missing 2.0.1 tag?

### ISSUE THREAD

**Issue by MichaelChirico** [jimhester/lintr#671]
The main page shows the "latest release" as 2.0.0 (Oct '19), and I don't see a 2.0.1 tag, but the current version in `DESCRIPTION` is 2.0.1.9999 and 2.0.1 is on CRAN

**Comment by AshesITR** [comment]
The commit must be 01e57c2124891b965c02626b27559c95f3218679.
It's with @russHyde as author, the checkstyle.xml is the same as on CRAN and it still contained the unneded [sic] misspell in unneeded_concatenation_linter.

**Comment by AshesITR** [comment]
I've created a draft release and added the tag after confirming the CRAN v2.0.1 tarball stems from this commit.

**Comment by russHyde** [comment]
This all seems fine. I'll publish the draft-release
