### ISSUE TITLE
terminal_newline_linter

### ISSUE THREAD

**Issue by MichaelChirico** [jimhester/lintr#675]
Add a linter which checks for terminal newlines in source.

Alternatively, we could extend/adjust `trailing_blank_lines_linter` to work for this case as well.

**Comment by AshesITR** [comment]
I like the idea of extending `trailing_blank_lines_linter` since it's so similar in functionality already.

**Comment by MichaelChirico** [comment]
agree, my only question is, is the name still appropriate? I guess it's
fine, wdyt?

**Comment by AshesITR** [comment]
Me too. It still looks at trailing blank lines.

**Comment by russHyde** [comment]
Crossref: #50

**Comment by AshesITR** [comment]
#562 made this trivial.
It should check if `terminal_newline` is `FALSE` and lint the last line, last column of the file.
The lint position would allow fixing the lint by jumping to its marker and hitting <kbd>Enter</kbd>
