### ISSUE TITLE
cyclocomp default: 15 or 25?

### ISSUE THREAD

**Issue by AshesITR** [jimhester/lintr#693]
Currently effective default linter is `cyclocomp_linter(complexity_limit = 15L)`:

https://github.com/jimhester/lintr/blob/2e1baab648a9baa5e1f48e2ca16b41a9b5559ebb/R/zzz.R#L80

However, the default argument says `cyclocomp_linter(complexity_limit = 25L)`

https://github.com/jimhester/lintr/blob/2e1baab648a9baa5e1f48e2ca16b41a9b5559ebb/R/cyclocomp_linter.R#L7

They should be synchronized imo. But what should be the default value?
15 is a lot stricter than 25.

We have one function `lint()` with a CC exceeding 25 (30) while there are 9 functions with a CC exceeding 15 (see #653)

Any thoughts?
cc @jimhester @russHyde @MichaelChirico

**Comment by russHyde** [comment]
I'd tighten them both to 15. Anyone using the defaults would be unaffected, anyone setting their own limit would be unaffected. The only pipelines affected would have 'linters: cyclocomp_linter' (or similar) with the linting function explicit but without arguments in the .lintr.

**Comment by jimhester** [comment]
I agree with @russHyde
