### ISSUE TITLE
Add renv and packrat to default-excluded directories

### ISSUE THREAD

**Issue by russHyde** [jimhester/lintr#697]
#492 
Suggest modifying the exclusions param  in lint_dir and linr_package to drop common directories (renv, packrat)

**Comment by AshesITR** [comment]
That usecase was the main motivation for me to code up the directory exclusion as well. The risk for unintended exclusion of those two is minimal so making them the default sounds like a good idea.

**Comment by AshesITR** [comment]
NB why would one use `renv` or `packrat` in a Package?
Maybe better to only add this default for `lint_dir`. WDYT?

**Comment by russHyde** [comment]
Sorry, you are right. I never use either.
