### ISSUE TITLE
typo: rstudioapi>=0.12 (not 0.2)

### ISSUE THREAD

**Issue by jhgoebbert** [jimhester/lintr#701]
The descriptions claims that rstudioapi is needed in version 0.2  

I suppose this is a typo and should be 0.12
https://github.com/jimhester/lintr/blob/master/DESCRIPTION#L23

**Comment by russHyde** [comment]
That prerequisite (>= 0.2) was set ~ 5 years ago & prior to rstudioapi=0.12. Are you having any issues using lintr with the version of rstudioapi that you have installed?

**Comment by jhgoebbert** [comment]
I was adding the package [languageserver](https://cran.r-project.org/web/packages/languageserver/index.html) to our [easybuild-module for R](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb) and was therefore checking the dependencies manually.
That was the reason why I came across the requirement rstudioapi>=0.2 [here](https://cran.r-project.org/web/packages/lintr/index.html) which I could not find ([rstudioapi](https://cran.r-project.org/web/packages/rstudioapi/index.html)).

So, it is just a typo in the documentation you might want to fix.  
I could install lintr without any issue with rstudioapi==0.13.

**Comment by russHyde** [comment]
You can find it in the cran release archive, if you need to check against rstudioapi v 0.2. Almost all your users will be using a more recent rstudioapi though.

**Comment by jhgoebbert** [comment]
Oh no, how stupid of me. Sorry, I was so lost in thought that I always saw 0.13 as 0.1.3 in my mind's eye.
