### ISSUE TITLE
[Discussion] lintr 3.0.0 release?

### ISSUE THREAD

**Issue by AshesITR** [jimhester/lintr#718]
We've added a lot of new and exciting features to the current development version of lintr, to the point that some downstream users (including me) are using the github version because they need e.g. directory exclusions.

So I wonder, is it time for prepairing a new release of lintr?
I think the number of changes warrants a major version bump, so I suggest 3.0.0 to be the new version.

**Comment by MichaelChirico** [comment]
definitely agree we should try and triage open PRs/issues and push for a
release soon. we definitely need to bump minor version, I don't have a good
sense of whether major version should be bumped.

**Comment by AshesITR** [comment]
I looked at the current NEWS.md and found two changes, that might impact "off-label" usage of lintr:

 * exclusions are now relative to the `.lintr` file (they were relative to the caller wd before that):
   this could break code where a user conventionally calls e.g. `lint_package()` from outside the package and adapted the `.lintr` config to the previous (IMO quirky) behaviour
 * lints now have the linter name instead of the implementation name assigned:
   this could break contrived code where the names in `linters` are specified and later the `Lint` names used with the assumption that they are equal to the implementing functions, e.g. `linters = list(a = line_length_linter())` produced lints from the `line_length_linter` while it now produces lints from the `a` linter. This seems unlikely to have relevance in practice

**Comment by MichaelChirico** [comment]
Went ahead and created a milestone (`3.0.0`) to tag issues/PRs we'd like to close out for release.

**Comment by MichaelChirico** [comment]
LMK when we're about ready to freeze new features, I'll start a comparison of `HEAD` vs 2.0.1 on all CRAN

**Comment by AshesITR** [comment]
I think the most important open issue is #720 atm. If we agree to settle on the current implementation, I would try finishing all open milestone:3.0.0 PRs and start with release preparations.

**Comment by MichaelChirico** [comment]
Closing this in favor of tracking release in #824
