### ISSUE TITLE
[Discussion] High-level API for excluding specific linters

### ISSUE THREAD

**Issue by AshesITR** [jimhester/lintr#720]
@AshesITR sorry for the delay -- have been moving across the country since early December, finally getting settles with a good enough setup to do a review.

Some higher-level thoughts:

 1. Another good follow-up would be the option to _force_ exclusions to use a list, i.e. generic `# nolint` is not allowed. Specifying the linter makes "lint creep" far less likely, and makes it easier to search out all instances of a specific lint to boot.
 2. The `: <linters>.` syntax looks a bit odd for `nolint: start: <linters>.` because the `:` is repeated. I still don't have a good alternative I'm happy with thought so not making it a blocker...
 3. Somewhat related, some people might like to namespace-tag the linter exclusions, e.g. I keep my custom lints in a package `myLinter` and it makes it clearer to readers to see `# nolint: lintr::seq_linter, myLinter::power_linter`. Probably another follow-up issue to file.
 4. Another power feature I think was mentioned at some point is non-overlapping range exclusions, e.g. `1:# nolint start: linterA` ... `5:# nolint start: linterB` `6: ...` `7: # nolint end: linterA` ... `12: # nolint end: linterB`. I think the logic is partway there to supporting this, but it's not necessary to get this merged.

_Originally posted by @MichaelChirico in https://github.com/jimhester/lintr/issues/660#issuecomment-769675032_

**Comment by AshesITR** [comment]
Thanks for you review, @MichaelChirico.
The GHA failure is due to the regex-based parsing of lint exclusions, i've tried fixing it by tricking with the \code command.

re 1.: crossref #690

re 2.: `# nolint: start` doesn't work by default, one might simply change the `exclude_linter` setting to a more pleasant regex as well.

The default is

    ^[[:space:]]*:[[:space:]]*(?<linters>(?:(?:[^,.])+[[:space:]]*,[[:space:]]*)*(?:[^,.])+)\.

What might work here (accepting `# nolint: start (bla_linter)`, `# nolint (bla_linter)`) might be using `(...)` instead of `:.. .`

    ^[[:space:]]*\([[:space:]]*(?<linters>(?:(?:[^,.])+[[:space:]]*,[[:space:]]*)*(?:[^,.])+)\)

re 3.: The way we currently work is we take the name of the linter from the `linters` list. How does auto-naming work with custom linters? IINM the namespacing would be unnecessary. Not sure how to make this work with custom names either, imagine
`list(linter_a = myPkg::a_linter(option = "a"), linter_b = myPkg::a_linter(option = "b"))`

re 4.: This would be a breaking change once we publish, since it changes the semantics of e.g.

    # nolint start: a.
    # nolint start: b.
    # nolint end
    code_with_lint_type_a
    # nolint end

Will throw a type `a` lint in the current implementation but won't if we add the "scoping" feature you propose.
Unless we would require # nolint end to be specific as well, in which case the new implementation should complain about a duplicate (unnecessary) # nolint end tag.

_Originally posted by @AshesITR in https://github.com/jimhester/lintr/issues/660#issuecomment-769996793_

**Comment by AshesITR** [comment]
The current API has a few implications:

1. There is no out-of-the box support for linters with a `.` in their name in the specific exclusions feature. This is due to the dot being used as the list terminator.  
Another sensible default option would be to make the syntax `# nolint (linter_1, linter_2)` instead of the currently implemented `# nolint: linter_1, linter_2.`
2. By allowing unspecified `# nolint end` tags, we can't later introduce scoping rules for nested `# nolint start` tags.  
If we want to keep this option open, we're basically forced to either implement it before an official release.

cc @MichaelChirico @russHyde @jimhester

**Comment by jimhester** [comment]
We might want to consider going with the similar format as [pylint](https://pylint.readthedocs.io/en/latest/faq.html#is-there-a-way-to-disable-a-message-for-a-particular-module-only)

which would imply something like `# lintr: disable=linter_1, linter2`.

I think it probably would be OK to require these to all be on a single line, which would avoid the need for an explicit terminator. If you do want a terminator using `;` might be most R like, as you can already use `;` to terminate expressions in R and it would avoid the issues with `.`.

**Comment by AshesITR** [comment]
Allright. I think we should have a terminator so that explaining comments can follow the linter list without causing unintended exclusions.

Note that `# lintr: disable=` would not be compatible with the old `# nolint` default for line exclusions. Do we really want to break this syntax?

If yes, the default could be `# lintr: disable` and the regions could be `# lintr: start disable` and `# lintr: end disable`. WDYT?

**Comment by jimhester** [comment]
I would think the regions would be `# lintr: disable` and `# lintr: enable`

**Comment by MichaelChirico** [comment]
FWIW we are already using exactly `# lintr: enable/disable` as our region markers.

btw, one concern of this is that `line_length_linter` doesn't exclude trailing comments, and this format tends to make wide lines. should we edit that linter? even if inline `# nolint`s become one-line regions (so the lintr list gets its own line), the exclusion list might need to spill over to another line. or else line_length_linter will often be added to the exclusion list

**Comment by AshesITR** [comment]
> I would think the regions would be `# lintr: disable` and `# lintr: enable`

This would make nolint starts indistinguishable from nolints.

**Comment by MichaelChirico** [comment]
Would setting the linter list terminator characers as options configurable in `.lintr` help solve this issue?

**Comment by AshesITR** [comment]
That's already possible with the `exclude_linter`option - mind the trailing `\.` in [my second comment](https://github.com/jimhester/lintr/issues/720#issuecomment-770278872)

**Comment by AshesITR** [comment]
Closing now since alternatives can easily be configured user-side by modifying the regexes.
