### ISSUE TITLE
Unified linter function interface

### ISSUE THREAD

**Issue by AshesITR** [jimhester/lintr#733]
I really like the ideas from #245. ~~Unfortunately, the codebase has diverged extremely from the PR branch to the point that I think a complete rewrite of #245 starting from master is less work.~~
I've merged current master into #245 to get the PR up to speed.

Do we want to include this interface overhaul in 3.0.0?

**Comment by MichaelChirico** [comment]
Agree it should be included, especially since we plan a major version bump. now is the time to try and include any pending issues which we think are worth breaking changes.
