### ISSUE TITLE
Error in source_file$lines[[line_number]] : subscript out of bounds

### ISSUE THREAD

**Issue by liar666** [jimhester/lintr#748]
Using:
R "4.0.3"
lintr  "2.0.1"

R> library(lintr)
R> lintr("myfile.R")
Error in source_file$lines[[line_number]] : subscript out of bounds

- myflie.R
```myflie.R
test = function(a,e,r,c=10,ze,r,t) {
    return 10+"coucou"
}
```
My test file is voluntarily buggy as I'm experimenting with lsp-r/eglot in Emacs.

Both Emacs & R packages are up-to-date w/r CRAN Lyon 2 repo

**Comment by MichaelChirico** [comment]
can you please retry on the current dev version? I recently saw a similar
error using the CRAN version that didn't reproduce at HEAD

**Comment by liar666** [comment]
That works. Thanks a lot!
Do you know if there's a mean to push an updated version on CRAN?

**Comment by MichaelChirico** [comment]
you can track the 3.0.0 milestone; an update will probably (?) happen sometime this or next month.
