### ISSUE TITLE
lint_dir ignores .lintr file

### ISSUE THREAD

**Issue by nlarusstone** [jimhester/lintr#769]
When running `lint_dir` from within the `Rstudio` console, it ignores the settings in my `.lintr` file.

Reprex
Here's my repo structure
```
├── .lintr
├── R
│   ├── ignored.R
│   └── linted.R
└── foo.Rproj
```

Contents of `ignored.R` and `linted.R` are the same:
```
print("this line is over 100 characters so it will trigger the linter and cause an error to be reported")
```

Here's my `lintr` file:
```
linters: with_defaults(
  line_length_linter(100)
  )
exclusions: c(
    "R/ignored.R"
    )

```

**Comment by AshesITR** [comment]
Thanks for reporting this. Can you reproduce the problem with the current development version of lintr?
You can install it with `devtools::install_github("jimhester/lintr")`.

**Comment by nlarusstone** [comment]
```r
> packageVersion("lintr")
[1] ‘2.0.1.9000’
```
Yes, that seems to fix it. Feel free to close when it's released!

**Comment by AshesITR** [comment]
Thanks for testing this. Closing now as it's fixed in the current development version. Feel free to subscribe to the 3.0.0 milestone to get a release notification.
