### ISSUE TITLE
Space before parenthesis: c((x + y) * z)

### ISSUE THREAD

**Issue by krlmlr** [jimhester/lintr#77]
```
## R/id.r:51:14: style: Place a space before left parenthesis, except in a function call.
##     res <- c((mat - 1L) %*% combs + 1L)
##              ^
```

After adding the space:

```
## R/id.r:34:13: style: Do not place spaces around code in parentheses or square brackets.
##     res <- c( (mat - 1L) %*% combs + 1L)
##             ^
```

One of both has to give in here. Perhaps similar to #75.

**Comment by jimhester** [comment]
Agreed, I guess of the two options I prefer the former, so we will have to special case multiple `(` I guess.

**Comment by richfitz** [comment]
Might be worth a special case for things like `!` too? I feel that

```
if (!(foo && bar || baz)) {
```

is more common than

```
if (! (foo && bar || baz)) {
```

**Comment by jimhester** [comment]
Yeah we need to rework the logic of this linter, `if (!(foo && bar || baz)) ` is definitely preferred.

**Comment by yu-iskw** [comment]
How about `:` before a left parentheses, such as `1:(len(array) - 1)`? 
I think it would be more common than `1: (len(array) - 1)`.

**Comment by jimhester** [comment]
All of these cases do not produce lints in the latest master, but I added tests for them to prevent regressions.
