### ISSUE TITLE
Token for assignment pipe 

### ISSUE THREAD

**Issue by ishaar226** [jimhester/lintr#770]
Hi, 
I was wondering if there was a token for the assignment pipe, as I am trying to make a linter that checks for assignment pipe usage. 
I had also just tried this: lapply(ids_with_token(source_file,"'%<>%'")
Here is the entire assignment_pipe_linter.R and the test file I made for it (which it does not lint properly). 

[AssignmentPipeLinter.zip](https://github.com/jimhester/lintr/files/6032648/AssignmentPipeLinter.zip)

**Comment by MichaelChirico** [comment]
all infix operators are SPECIALs, look for that and check %<>% in the text()

**Comment by ishaar226** [comment]
Hi, 
Thank you for the quick response
Instead of "'%<>%'", I used `ids_with_token(source_file,"SPECIAL")`
But I'm not sure what exactly you mean by going to check %<>% in the text() - could you provide a sample code or description of what you mean?

**Comment by MichaelChirico** [comment]
Hmm that was extemporaneous & I was thinking in terms of the XML parse tree
-- not sure what the relevant equivalent is from the parse data.frame.

But you can check

utils::getParseData(parse(text = 'x %<>% foo'))

to see what's going on in a minimal example

**Comment by ishaar226** [comment]
Special tokens are for all infix operators - for example, I only want to lint the assignment pipe operator (%<>%), but I wouldn't want to lint %in% or any other infix operators. So using the SPECIAL token in the `ids_with_token(source_file,"SPECIAL")`  wouldn't really solve my issue at hand. I was wondering though if you know how to rectify this or search the parsed data directly?

**Comment by MichaelChirico** [comment]
Consider:

```
parseData = utils::getParseData(parse(text = "x %<>% y"))
subset(parseData, token == "SPECIAL" & text == "%<>%")
#  line1 col1 line2 col2 id parent   token terminal text
# 2     1    3     1    6  2      7 SPECIAL     TRUE %<>%
```

BTW, if all you're trying to do is write a linter to block `%<>%` from being used, you can use `lintr::undesirable_operator_linter` for that already:

```
lintr::lint("x %<>% y\n", lintr::undesirable_operator_linter(c("%<>%" = "don't use")))
<text>:1:3: warning: Operator `%<>%` is undesirable. As an alternative, don't use.
x %<>% y
  ^~~~
```

**Comment by MichaelChirico** [comment]
I hope that answers your issue, sorry not to have given a fuller response before as I was answering from mobile.

Closing, but feel free to re-open if there are residual concerns.
