### ISSUE TITLE
lintr::lint() crashes R

### ISSUE THREAD

**Issue by nlarusstone** [jimhester/lintr#772]
Originally opened under https://github.com/rstudio/rstudio/issues/9050

Running `lintr::lint(<FILE>)` crashes R 4.0.3 when there are lints

```
> library("lintr")
> lintr::lint("bar/foo.R")
~/bar/foo.R:26:37: style: Put spaces around all infix operators.
    quiet <- quiet_drm(formula, data=df,
...
~/bar/foo.R:49:56: style: Only use double-quotes.
  tidyr::separate(ret, term, c("term", "curve"), sep = ':')
  
~/Code/platform master 13s
pipeline ❯  
```

**Comment by MichaelChirico** [comment]
Thanks! Two quick follow-ups to help guide debugging:

(1) does the issue reproduce when running inside a plain R terminal (i.e.
outside rstudio)

(2) can you confirm your lintr and rstudio versions?

**Comment by MichaelChirico** [comment]
Sorry I just read the rstudio issue & saw it's not an rstudio thing so scratch (1)

**Comment by AshesITR** [comment]
@nlarusstone Can you provide us with a file that reproduces the issue on the current development version of `lintr`?
Otherwise, we're unlikely to be able to help you.

**Comment by nlarusstone** [comment]
I can't seem to reproduce with a single file, only in my main environment

I'm currently using `lintr` version `2.0.1`

**Comment by AshesITR** [comment]
Can you try `devtools::install_github("jimhester/lintr")` to check the current development version and report back?
Thanks!

**Comment by AshesITR** [comment]
Closing for now. Feel free to reopen if you can reproduce on the current dev version of lintr with a file that you can share.
