### ISSUE TITLE
Suspicious state from syntax checker ...

### ISSUE THREAD

**Issue by yitang** [jimhester/lintr#79]
Hi, `lintr` works well on OSX but I have problem in getting it works in UBUNTU, although the same configuration are used in both machines, 

``` emacs-lisp
(require 'flycheck)
(add-hook 'ess-mode-hook
          (lambda () (flycheck-mode t)))
(load "~/git/.emacs.d/lisp/lintr.el")
```

I got this error message all the time and i have to disable flycheck mode. 

```
Suspicious state from syntax checker r-lintr: Checker r-lintr returned non-zero exit code 1, but no errors from output: Error in if (low > 0L) { : missing value where TRUE/FALSE needed
Calls: lint -> retrieve_lint -> lapply -> FUN -> find_new_line
In addition: Warning messages:
1: In readLines(filename) :
  incomplete final line found on '/tmp/flycheck3790mvZ/tmp.R'
2: In readLines(filename) :
  incomplete final line found on '/tmp/flycheck3790mvZ/tmp.R'
Execution halted

Checker definition probably flawed.
``` 

Do you have any ideal what's wrong? 

-Yi

**Comment by jimhester** [comment]
With recent versions of flycheck lintr is bundled by default, so you likely don't need to load the lintr.el script anymore.  Try removing it and see if it works.

I am using Ubuntu currently so I can confirm lintr with emacs does work on at least one Ubuntu machine :smile:

**Comment by yitang** [comment]
Hi,

Thanks, I changed the configuration to 
``` emacs-lisp
(require 'flycheck)
(add-hook 'ess-mode-hook
          (lambda () (flycheck-mode t)))
```

now it is quiet, but actually doing nowthing, i tried 

``` r
x = 123
``` 

and it does not notify me to change `=` to `<-`. I am sure the `flycheck-check` mode is enabled.

**Comment by jimhester** [comment]
I think there is a bug currently with the lintr cache and emacs.  If you
add ` '(flycheck-lintr-caching nil)` try adding to your configuration and
see if it works then.

**Comment by yitang** [comment]
Hi,

it works! but only in one buffer, the other is still showing nothing. Actually none of them is working now, after I saved them... 

Should I close all Emacs and try it again?

**Comment by jimhester** [comment]
Probably closing and restarting would be the best option once you have
turned off caching

**Comment by yitang** [comment]
emmmm, still not working, nothing happening. 

``` emacs-lisp 
(require 'flycheck)
'(flycheck-lintr-caching nil)
(add-hook 'ess-mode-hook
          (lambda () (flycheck-mode t)))
``` 

btw, the version of flycheck in my machine is 20150409.1217 if it helps.

**Comment by lgatto** [comment]
Same version, same problem, here. 

If I `rm -r ~/.R` and restart `emacs bad.R`, then it works for a moment and, as soon as I edit the ESS buffer it stops working and `~.R/lintr_cache/bad.R` is again present. 

My relevant config is as follows
```el
(require 'flycheck)
(add-hook 'after-init-hook #'global-flycheck-mode)
'(flycheck-lintr-caching nil)
```

**Comment by lgatto** [comment]
It seem that customising `flycheck-lintr-caching` directly trough emacs does work. I got there through `M-x flycheck-describe-checker` -> `r-lintr`, then select `flycheck-lintr-caching` and toggle state.

**Comment by yitang** [comment]
@lgatto Tried your method, it works in my case.
