### ISSUE TITLE
linter weighting?

### ISSUE THREAD

**Issue by MichaelChirico** [jimhester/lintr#811]
Sometimes we get multiple lints on a given line. If a display tool is limited to showing only one lint, right now, there's no systematic way to prioritize which is shown.

This might be important if there are multiple overlapping lints that point to slightly different fixes, e.g.

 - `expect_lt_linter` looks for `expect_true(x < 5)` to be `expect_lt(x, 5)`
 - `expect_eq_linter` looks for `expect_true(abs(x - y) < 1)` to be `expect_equal(x, y, tolerance=1)`

Any code failing `expect_eq_linter` also fails `expect_lt_linter`, but the former "has higher priority" since we'd rather fix that one than do `expect_lt(abs(x-y), 1)`*.

It should be possible to set up an API for adding weights to the linters (probably through the `.lintr` config so that this can be customized, default is equal weighting) -- I guess the main question is whether this would be in scope for `lintr` or delegated to an add-on?

\*One could extend `expect_eq_linter` to also look for usage like `expect_lt(abs(x-y), 1)`, which is basically OK, though slightly inconvenient to users who might fix code only for it to still be broken. Matryoshka linting 😃

**Comment by AshesITR** [comment]
Out of curiosity, can the order of the lints currently be controlled by changing the linter order in `linters`?
If so, that would be a very simple way to define priorities.
Depending on the consumer, one could move the important linters to the front of the list of lints or to the back.

IMO explicitly setting priorities is a clunky interface and can lead to duplicate "weights".
If the "weights" are instead somehow based on the order of linters in the config, it would be trivial to modify and we could easily define the default weighting by ordering default_linters appropriately.
WDYT?

**Comment by MichaelChirico** [comment]
that sounds great, good idea. I haven't had a chance to test but I think you're right. closing for now.
