### ISSUE TITLE
Include x <- {} in unneeded_concatenation_linter?

### ISSUE THREAD

**Issue by MichaelChirico** [jimhester/lintr#817]
Both of the following have the same effect:

```
x <- c()
y <- {}
identical(x, y)
# [1] TRUE
```

The first is linted by `unneeded_concatenation_linter`; would it make sense to include the latter there as well?

**Comment by AshesITR** [comment]
Well, `{}` is an empty code block, not an unneeded concatenation.
Also note that with tidyeval syntax, `df %>% select({{ symbol }})` is perfectly fine code.

**Comment by MichaelChirico** [comment]
Good point, OK I will write a more specific linter for my use case then.
