### ISSUE TITLE
get_source_expression() column correction

### ISSUE THREAD

**Issue by AshesITR** [jimhester/lintr#819]
When incorporating the fix #816 into my Encoding PR #782, I noticed test failures locally (they didn't pop up in CI :().

Digging deeper made me wonder if `fix_column_numbers()` is actually needed anymore:

R 4.1.0 gives basically identical parse data for text with and without multibyte characters:

```r
getParseData(parse(text = "`x` <- 1"))
#  line1 col1 line2 col2 id parent       token terminal text
#7     1    1     1    8  7      0        expr    FALSE     
#1     1    1     1    3  1      3      SYMBOL     TRUE  `x`
#3     1    1     1    3  3      7        expr    FALSE     
#2     1    5     1    6  2      7 LEFT_ASSIGN     TRUE   <-
#4     1    8     1    8  4      5   NUM_CONST     TRUE    1
#5     1    8     1    8  5      7        expr    FALSE  
   
getParseData(parse(text = "`\U2020` <- 1"))
#  line1 col1 line2 col2 id parent       token terminal text
#7     1    1     1    8  7      0        expr    FALSE     
#1     1    1     1    3  1      3      SYMBOL     TRUE  `†`
#3     1    1     1    3  3      7        expr    FALSE     
#2     1    5     1    6  2      7 LEFT_ASSIGN     TRUE   <-
#4     1    8     1    8  4      5   NUM_CONST     TRUE    1
#5     1    8     1    8  5      7        expr    FALSE     
```

Tested on Linux and Windows.

Can anyone verify from what R version these Corrections are no longer needed?
@MichaelChirico maybe?
@jimhester The original code is from 2014, written by you. Maybe you remember some context?

**Comment by MichaelChirico** [comment]
I think that must be a recent change, IINM I was working on a similar issue & my R version was still affected.

You can try rocker/r-ver for a quick way to test on older versions (won't have time soon to try myself)

**Comment by AshesITR** [comment]
Thanks for the hint. I'll check.
Curious is that all checks for #782 fail the corresponding test - even on 3.4...

**Comment by jimhester** [comment]
The parser was fixed in some version of R many years later, I don't recall which.

**Comment by jimhester** [comment]
Actually I think the bug I was thinking of was https://bugs.r-project.org/bugzilla/show_bug.cgi?id=16041, which is another one I had to work around for lintr.

In any case I believe this one was also fixed by Tomas at some point.

**Comment by AshesITR** [comment]
Fond it. Thanks for the pointer.

>CHANGES IN R 3.4.1
>INSTALLATION on a UNIX-ALIKE
>
>    The deprecated support for PCRE versions older than 8.20 has been removed.
>
>BUG FIXES
>
>    getParseData() gave incorrect column information when code contained multi-byte characters. (PR#17254)

We no longer test R 3.3, so codecov won't allow keeping the old code path. Making a PR to remove the fix.

**Comment by AshesITR** [comment]
I could repro the result from the test case now

```r
getParseData(parse(text = `Encoding<-`("`\U2020` <- 1", "unknown")))
#  line1 col1 line2 col2 id parent       token terminal text
#7     1    1     1   10  7      0        expr    FALSE     
#1     1    1     1    5  1      3      SYMBOL     TRUE  `†`
#3     1    1     1    5  3      7        expr    FALSE     
#2     1    7     1    8  2      7 LEFT_ASSIGN     TRUE   <-
#4     1   10     1   10  4      5   NUM_CONST     TRUE    1
#5     1   10     1   10  5      7        expr    FALSE     
```

As can be seen, the problem is unmarked encoding of the source code.
If we mark the source code appropriately as UTF-8, all is well.
