### ISSUE TITLE
'LazyData' is specified without a 'data' directory

### ISSUE THREAD

**Issue by AshesITR** [jimhester/lintr#827]
From the [current CRAN check results](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/lintr-00check.html)

```
checking LazyData ... NOTE
  'LazyData' is specified without a 'data' directory
```

I think removing `LazyData: true` from `DESCRIPTION` should be fine.

**Comment by MichaelChirico** [comment]
looks like it's been there since the initial commit, probably a copy paste
vestige & unearthed by a new CRAN check? I don't see a data directory in
the tree then
