### ISSUE TITLE
Move {httr} to `Suggests:`

### ISSUE THREAD

**Issue by lorenzwalthert** [jimhester/lintr#861]
Seems like {httr} is only used [once](https://github.com/jimhester/lintr/blob/c2135e2e0dc75ba4b8eba38f868169f26481be64/R/comments.R#L62) to interact with the GitHub API, which I think is not core functionality of {lintr}. The hard-reverse dependency graph could be reduced by 6 packages and two system dependencies (curl and openssl).

Would you consider making {httr} a suggested package only?

``` r
imports <- c("rex", "crayon", "codetools", "cyclocomp", "testthat", "digest", "rstudioapi", "httr", "jsonlite", "knitr", "stats", "utils", "xml2" , "xmlparsedata")
current <- miniCRAN::pkgDep(imports, suggests = FALSE)
#> Warning in miniCRAN::pkgDep(imports, suggests = FALSE): Package not recognized:
#> stats, utils
withotu_httr <- miniCRAN::pkgDep(setdiff(imports, 'httr'), suggests = FALSE)
#> Warning in miniCRAN::pkgDep(setdiff(imports, "httr"), suggests = FALSE): Package
#> not recognized: stats, utils
setdiff(current, withotu_httr)
#> [1] "httr"    "curl"    "mime"    "openssl" "askpass" "sys"
```

<sup>Created on 2021-09-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Background: When running {lintr} on CI/Cd with https://github.com/lorenzwalthert/precommit, we want to bring down install time (plus avoid system dependencies).

**Comment by MichaelChirico** [comment]
Filed as #863, thanks for the suggestion!

FWIW, we could also bump `testthat` to Suggests IMO. It's only in Imports for its use in `expect_lint()` (which is heavily dependent on `testthat`), but I think you can get plenty of mileage out of `lintr` without ever needing `expect_lint()`.

The delta from dropping `testthat` would be much larger than from `httr` -- 17 packages, including some heavy ones:

```
 [1] "testthat"  "brio"      "cli"       "ellipsis"  "lifecycle" "pkgload"   "praise"   
 [8] "rlang"     "waldo"     "diffobj"   "fansi"     "rematch2"  "tibble"    "pillar"   
[15] "pkgconfig" "vctrs"     "utf8"    
```

What do the other maintainers think?

**Comment by AshesITR** [comment]
Sounds good to me. Package developers will most likely have `testthat` installed anyway and end users don't need `expect_lint()`.
