### ISSUE TITLE
Deprecated trailing_semicolons_linter doesn't work

### ISSUE THREAD

**Issue by MichaelChirico** [jimhester/lintr#862]
```
lintr::lint("a <- 2;\n", lintr::trailing_semicolons_linter())
# Error in semicolon_terminator_linter(semicolon = "trailing")(source_file) : 
#   argument "source_file" is missing, with no default
```

The issue is the call tries to evaluate `semicolon_terminator_linter` instead of returning a function factory.

It's an easy fix, but it also raises the question -- should we just delete this? It's marked as deprecated since ~1.0.1 (4 years ago).

**Comment by AshesITR** [comment]
I'd go for deletion. It will be the second major CRAN release after deprecation.
