### ISSUE TITLE
onload_package_startup_linter for packageStartupMessage() inside .onLoad()?

### ISSUE THREAD

**Issue by MichaelChirico** [jimhester/lintr#882]
Using `packageStartupMessage()` in the `.onLoad()` hook is an `R CMD check` `NOTE`. So I think it makes sense to offer a linter to detect that as an early warning.

**Comment by AshesITR** [comment]
This seems useful but oddly specific.
Are there similar detectable problems? e.g. using `message()` in `.onLoad` or `.onAttach`?

**Comment by MichaelChirico** [comment]
I'll experiment later, but from my read it really only is `packageStartupMessage()` in `.onLoad()`:

https://github.com/wch/r-source/blob/8b6625e39cd62424dc23399dade37f20fa8afa91/src/library/tools/R/QC.R#L5167

The line before suggests we could include `library.dynam()` calls in `.onAttach()` as well... we could add that & rename it as `ns_hook_usage_linter`? WDYT?

**Comment by AshesITR** [comment]
What about `package_startup_linter` as a name and we also check, e.g. 

https://github.com/wch/r-source/blob/8b6625e39cd62424dc23399dade37f20fa8afa91/src/library/tools/R/QC.R#L5254-L5267

**Comment by MichaelChirico** [comment]
Nice! Good idea
