### ISSUE TITLE
Lintr not picking up exclusions list in lint_dir

### ISSUE THREAD

**Issue by telegott** [jimhester/lintr#885]
First of all, thanks for this awesome package! Definitely helping in promoting good practices! :) 
I have a regular R project setup with an `.Rproj` file and `renv` (not a package setup). I would like to run `lintr` as part of a Jenkins CI in the form of some script that returns `0` or `1` and `lintr::lint_dir()` seems like a good fit. The project looks like this:

```
├── the-project.Rproj
├── renv
│   ├── activate.R
│   ├── library
│   │   └── R-4.1
│   │       └── ...
│   ├── settings.dcf
│   └── staging
├── renv.lock
├── R
│   └── a_script.R
└── project_x
    └── evaluate_x.R
```

The problem now is that if I simply do `lint_dir()` from the project root, it will lint all R files under `renv`. I tried several flavours of `list(list.files(path = <path>, recursive = TRUE, full.names = TRUE))`, with `<path>` either being `renv` or more preferably `here::here("renv")` (in that case I also called `lint_dir(here::here())`, the script is always called from the project root.

I also tried without the `list()` wrapping `list.files()`, and looked at the steps the `lint_dir` function takes to exclude the files from the list, but never got the relevant block to exclude anything, despite the files found by `lint_dir` and the ones from the exclusion list seeming to have the same format.
I tried to provide the exclusion list either directly to `lint_dir` or in the `.lintr` file like e.g.

```
exclusions: list(list.files(path = here::here("renv"), recursive = TRUE, full.names = TRUE))
```
I saw in a similar issue that it might suffice to provide the folder name instead of full paths to files in the exclusion list, but also that did not work.
Am I understanding something wrong about the exclusion list?

**Comment by AshesITR** [comment]
The current development version supports directory exclusions, i.e. `exclustions: list("renv")` should work just fine.
Make sure to place it in the project root so `lintr` finds it.

**Comment by stufield** [comment]
I have a similar setup where I'm using `lint_dir()` in a unit testing setup (but I don't want to test the entire package). Couple ideas:

- have you tried ensuring the `.lintr` file is in DCF format? (see `README.md`)
```
exclusions: list(
  list.files(path = here::here("renv"), recursive = TRUE, full.names = TRUE)
  )
```
- which version of `lintr` are you using? In my setup `v2.0.0` failed to pick up the `.lintr` file using `lint_dir()`, but the current `dev` version behaves as expected.

**Comment by AshesITR** [comment]
@telegott could you resolve your problem by now?

**Comment by telegott** [comment]
Unfortunately, not yet. I'm using `lintr` 2.0.1:
```
- lintr          [* -> 2.0.1]
```
Is there anything special about the DCF format? My `.lintr` looks like
```
exclusions: list(
  list.files(here::here("renv"), recursive = TRUE, full.names = TRUE)
  )

```
(it complains about missing newlines if I move the `)` to the start of the line, so it picks it up.
I'm calling lintr with `lintr::lint_dir(here::here())`, no matter if I use 

```
exclusions: list(
  list.files(here::here("renv"), recursive = TRUE, full.names = TRUE)
  )

```
or 
```
exclusions: list("renv"))

```

It unfortunately it does not pick it up. The project currently 3 short `.R` files, so it should be really quick.

**Comment by AshesITR** [comment]
Can you check if `lintr:::find_config(".")` finds your config file?

**Comment by telegott** [comment]
Yes, it seems to do, because lintr also fails on a malformed `.lintr`. Here's the output:
```
print(lintr:::find_config("."))
"./.lintr"
print(lintr:::find_config(here::here()))
<the-full-path>/.lintr"
``

**Comment by AshesITR** [comment]
Can you `debug(lintr:::read_settings("."))` and see where it goes wrong?
Especially `read.dcf(".lintr", all = TRUE)` might help.

**Comment by telegott** [comment]
```
> read.dcf(".lintr", all = TRUE) 
                                                                     exclusions
1 list(\nlist.files(here::here("renv"), recursive = TRUE, full.names = TRUE)\n)
```

However, 
```
> settings=lintr:::read_settings(".")
> settings
NULL
```
Doesn't `read_settings(".")` get a file to be linted? If I provide one, it also doesn't change however.
Looking at the source of `read_settings`, if I run e.g. `lintr:::find_config("tests/lint.R")`, it finds the correct config, and it also then does the `read.dcf` part. From there on, it's a bit hard to trace down further

**Comment by AshesITR** [comment]
`read_settings()` doesn't return the settings, it writes them to `lintr:::settings`.
And yes, it gets the script filename as an argument, but `find_config()` traverses parent directories, so `"."` is also fine.

**Comment by stufield** [comment]
Have you tried the development version? I notice you said you're using `v2.0.1`, but for me I needed `> v2.0.1`.

**Comment by telegott** [comment]
@stufield indeed, the development version resolved the issues, I couldn't get it to work with the current CRAN version. Nice to see this is upcoming, thanks everyone!
