### ISSUE TITLE
Cannot fin lintr exutables

### ISSUE THREAD

**Issue by rudvfaden** [jimhester/lintr#89]
I'm trying to get this to work with sublime text. In the installation guide it says that I have to find the linter executables. However, I do not seem to be able to find any `lintr` exutable files. What is that I am missing?

**Comment by jimhester** [comment]
Install the lintr package https://github.com/jimhester/SublimeLinter-contrib-lintr#linter-installation and make sure R is in your `PATH`, then it should work.

If after doing that it doesn't seem to be working you should try turning off caching (Right Click->SublimeLinter->Open User Settings->user->linters->lintr->cache->FALSE).

**Comment by rudvfaden** [comment]
Yes. Okay. Got i working for a moment. But as soon as I start editing it
stops working and I get the error

SublimeLinter: lintr output:
Error in if (low > 0L) { : missing value where TRUE/FALSE needed
Calls: lint -> retrieve_lint -> lapply -> FUN -> find_new_line

If I then delete the ~/.R folder it works agian until I start to edit.
​

On Tue, May 19, 2015 at 4:55 PM, Jim Hester <notifications@github.com>
wrote:

> Install the lintr package
> https://github.com/jimhester/SublimeLinter-contrib-lintr#linter-installation
> and make sure R is in your PATH, then it should work.
>
> If after doing that it doesn't seem to be working you should try turning
> off caching (Right Click->SublimeLinter->Open User
> Settings->user->linters->lintr->cache->FALSE).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jimhester/lintr/issues/89#issuecomment-103536322>.
>



-- 
Rud

**Comment by jimhester** [comment]
You need to turn of the caching, see the instructions on the previous post.
