### ISSUE TITLE
object_usage_linter (and probably others) use namespace of installed package

### ISSUE THREAD

**Issue by krlmlr** [jimhester/lintr#91]
Local changes to the `NAMESPACE` file are reflected only after package is installed. To reproduce:

``` sj
pkgname="lintr.namespace.test"
rm -rf $pkgname
Rscript -e "devtools::create('$pkgname')"
Rscript -e "devtools::install('$pkgname')"
echo "a <- function() {" > $pkgname/R/a.R
echo "  llply" >> $pkgname/R/a.R
echo "}" >> $pkgname/R/a.R
echo "importFrom(plyr,llply)" > $pkgname/NAMESPACE

# Uncomment line below to fix error
#Rscript -e "devtools::install('$pkgname')"

Rscript -e "lintr::lint_package('$pkgname')"
```

An equivalent R script didn't exhibit the same error, so this one might be difficult to test automatically.

**Comment by jimhester** [comment]
I am aware of this deficiency, but an unsure how to remedy it.  The object_usage_linter loads the package namespace to check for defined globals, however the package actually needs to be installed in order for the namespace to be updated.  It could use `devtools::load_all()` to load the namespace, but that unfortunately has issues with some packages (particularly S4 packages) and has some weird edge cases.  But maybe `load_all()` is the way to go here...
