### ISSUE TITLE
Wrong warning of trailling whitespace

### ISSUE THREAD

**Issue by rudvfaden** [jimhester/lintr#92]
I get some errors in the begining of my document about trailling white space, even though there is none
![screenshot from 2015-06-01 13 07 24](https://cloud.githubusercontent.com/assets/2445577/7911545/559abf48-085f-11e5-8d4d-e0b3c75ba44a.png)

**Comment by jimhester** [comment]
Make sure there are no syntax errors elsewhere in your document, sometimes I get artifacts like this when there are R syntax errors elsewhere.  If that does not fix the problem please

1. run `lintr::lint()` directly on the file to see if the lints produced recapitulate the ones from the plugin.
1. Provide a link to an example document which reproduces the error.

Sorry for the issue!

**Comment by rudvfaden** [comment]
I get the same errors when I run `lintr`directly on the file. You can downloade the file [here](https://db.tt/g45o4MdA)

**Comment by bziepert** [comment]
I ran into the same problem today. In the file of @rudvfaden are trailing white spaces in 8:46, 39:40, 40:45, 56:25. If you remove them the trailing whitespace warning disappears. Still the trailing whitespaces are reported on the wrong lines:

yder-cvr.R:1:40: style: Trailing whitespace is superfluous.
yder-cvr.R:1:46: style: Trailing whitespace is superfluous.
yder-cvr.R:2:45: style: Trailing whitespace is superfluous.
yder-cvr.R:3:25: style: Trailing whitespace is superfluous.

This means the character position is right but the line position is wrong.

**Comment by yech1990** [comment]
got the same error.
![image](https://user-images.githubusercontent.com/5415510/56458884-a2561f80-63be-11e9-92f6-31031306e26b.png)
