### ISSUE TITLE
Update the CRAN version from 0.2 to 0.3

### ISSUE THREAD

**Issue by yu-iskw** [jimhester/lintr#98]
It seems that the CRAN version is 0.2.0. However, the latest version on github is 0.3.0+. Do you have any plan to update the CRAN version?

## CRAN

http://cran.r-project.org/web/packages/lintr/index.html

## Github Version

```
> packageVersion("lintr")
[1] ‘0.3.0.9002’
```

**Comment by jimhester** [comment]
Eventually, dealing with CRAN is usually a headache so I tend to avoid releasing there too often.  Thank you for the reminder however.

**Comment by yu-iskw** [comment]
Alright. Thank you for answering my question.
